# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status'], name='idx_inquiry_status'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['priority'], name='idx_inquiry_priority'),
        ),
    ]
