# Generated by Django 5.2.12 on 2026-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_inquiry_idx_inquiry_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-pk'], 'verbose_name': '문의', 'verbose_name_plural': '문의'},
        ),
    ]
