# Generated by Django 5.2.12 on 2026-04-15 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_inquiry_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'received_date'], name='idx_inquiry_status_date'),
        ),
    ]
