# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_serialnumber_idx_serial_status_date_and_more'),
        ('qms', '0002_alter_auditfinding_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['status', 'due_date'], name='idx_capa_status_due'),
        ),
        migrations.AddIndex(
            model_name='capa',
            index=models.Index(fields=['type', 'status'], name='idx_capa_type_status'),
        ),
        migrations.AddIndex(
            model_name='internalaudit',
            index=models.Index(fields=['status', 'audit_date'], name='idx_audit_status_date'),
        ),
        migrations.AddIndex(
            model_name='isodocument',
            index=models.Index(fields=['status', 'effective_date'], name='idx_isodoc_status_date'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['status', 'created_at'], name='idx_nc_status_date'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['severity', 'status'], name='idx_nc_severity_status'),
        ),
    ]
