# Generated by Django 6.0.3 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproductionplan",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="실제원가"
            ),
        ),
        migrations.AddField(
            model_name="historicalproductionplan",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="예상원가"
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="실제원가"
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="예상원가"
            ),
        ),
    ]
