# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_idx_product_type_and_more'),
        ('production', '0002_historicalproductionplan_actual_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['status'], name='idx_plan_status'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['planned_start'], name='idx_plan_start'),
        ),
        migrations.AddIndex(
            model_name='productionrecord',
            index=models.Index(fields=['record_date'], name='idx_record_date'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='idx_wo_status'),
        ),
    ]
