# Generated by Django 5.2.12 on 2026-03-19 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_bomitem_bom_historicalbomitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomitem",
            name="loss_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="손실률(%)",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="소요량",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbomitem",
            name="loss_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="손실률(%)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbomitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="소요량",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductionplan",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="실제원가",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductionplan",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="예상원가",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="실제원가",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="예상원가",
            ),
        ),
    ]
