# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_bomitem_loss_rate_alter_bomitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductionplan',
            name='plan_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='계획번호'),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='작업지시번호'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='plan_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='계획번호'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='작업지시번호'),
        ),
    ]
