# Generated by Django 5.2.12 on 2026-03-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_number_convert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ['-plan_number'], 'verbose_name': '생산계획', 'verbose_name_plural': '생산계획'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-order_number'], 'verbose_name': '작업지시', 'verbose_name_plural': '작업지시'},
        ),
        migrations.AddField(
            model_name='bomitem',
            name='production_qty',
            field=models.PositiveIntegerField(default=0, help_text='구매수량으로 생산 가능한 완제품 수', verbose_name='생산가능수량'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='purchase_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='1회 구매 단위 수량', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='구매수량'),
        ),
        migrations.AddField(
            model_name='historicalbomitem',
            name='production_qty',
            field=models.PositiveIntegerField(default=0, help_text='구매수량으로 생산 가능한 완제품 수', verbose_name='생산가능수량'),
        ),
        migrations.AddField(
            model_name='historicalbomitem',
            name='purchase_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='1회 구매 단위 수량', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='구매수량'),
        ),
    ]
