# Generated by Django 5.2.12 on 2026-03-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_record_warehouse'),
        ('production', '0008_add_bom_purchase_production_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductionrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='완제품 입고 및 원자재 출고 대상 창고', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='입고창고'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='완제품 입고 및 원자재 출고 대상 창고', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='입고창고'),
        ),
    ]
