# Generated by Django 5.2.12 on 2026-03-22 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_add_record_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductionrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산 시점 제품 원가 (자동 기록)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='생산단가'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산 시점 제품 원가 (자동 기록)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='생산단가'),
        ),
    ]
