# Generated by Django 5.2.12 on 2026-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_historicalproductionrecord_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'ordering': ['pk'], 'verbose_name': 'BOM 항목', 'verbose_name_plural': 'BOM 항목'},
        ),
    ]
