# Generated by Django 5.2.12 on 2026-03-23 04:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_historicalwarehousestock_warehousestock'),
        ('production', '0011_alter_bomitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalQualityInspection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('inspection_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='검수번호')),
                ('inspection_type', models.CharField(choices=[('PRODUCTION', '생산검수'), ('INCOMING', '입고검수')], default='PRODUCTION', max_length=15, verbose_name='검수유형')),
                ('inspected_quantity', models.PositiveIntegerField(verbose_name='검수수량')),
                ('pass_quantity', models.PositiveIntegerField(default=0, verbose_name='합격수량')),
                ('fail_quantity', models.PositiveIntegerField(default=0, verbose_name='불합격수량')),
                ('inspection_date', models.DateField(verbose_name='검수일')),
                ('result', models.CharField(choices=[('PENDING', '대기'), ('PASS', '합격'), ('FAIL', '불합격'), ('CONDITIONAL', '조건부합격')], default='PENDING', max_length=15, verbose_name='결과')),
                ('defect_description', models.TextField(blank=True, verbose_name='불량 내용')),
                ('corrective_action', models.TextField(blank=True, verbose_name='시정 조치')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='검수자')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('production_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionrecord', verbose_name='생산실적')),
            ],
            options={
                'verbose_name': 'historical 품질검수',
                'verbose_name_plural': 'historical 품질검수',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('inspection_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='검수번호')),
                ('inspection_type', models.CharField(choices=[('PRODUCTION', '생산검수'), ('INCOMING', '입고검수')], default='PRODUCTION', max_length=15, verbose_name='검수유형')),
                ('inspected_quantity', models.PositiveIntegerField(verbose_name='검수수량')),
                ('pass_quantity', models.PositiveIntegerField(default=0, verbose_name='합격수량')),
                ('fail_quantity', models.PositiveIntegerField(default=0, verbose_name='불합격수량')),
                ('inspection_date', models.DateField(verbose_name='검수일')),
                ('result', models.CharField(choices=[('PENDING', '대기'), ('PASS', '합격'), ('FAIL', '불합격'), ('CONDITIONAL', '조건부합격')], default='PENDING', max_length=15, verbose_name='결과')),
                ('defect_description', models.TextField(blank=True, verbose_name='불량 내용')),
                ('corrective_action', models.TextField(blank=True, verbose_name='시정 조치')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='검수자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='제품')),
                ('production_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='production.productionrecord', verbose_name='생산실적')),
            ],
            options={
                'verbose_name': '품질검수',
                'verbose_name_plural': '품질검수',
                'ordering': ['-inspection_date', '-pk'],
            },
        ),
    ]
