# Generated by Django 5.2.12 on 2026-03-23 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_category_parent_and_more'),
        ('production', '0012_historicalqualityinspection_qualityinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['-created_at'], 'verbose_name': 'BOM', 'verbose_name_plural': 'BOM'},
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='uq_bom_product_version'),
        ),
    ]
