# Generated by Django 5.2.12 on 2026-03-23 08:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_historicalproduct_reserved_stock_and_more'),
        ('production', '0013_alter_bom_options_alter_bom_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductionrecord',
            name='actual_labor_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제노무비'),
        ),
        migrations.AddField(
            model_name='historicalproductionrecord',
            name='actual_material_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제자재원가'),
        ),
        migrations.AddField(
            model_name='historicalproductionrecord',
            name='actual_overhead_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제간접비'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='actual_labor_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제노무비'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='actual_material_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제자재원가'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='actual_overhead_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제간접비'),
        ),
        migrations.CreateModel(
            name='HistoricalStandardCost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('effective_date', models.DateField(verbose_name='적용일')),
                ('material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준자재원가')),
                ('direct_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='직접노무시간')),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='시간당 노무비')),
                ('labor_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준노무비')),
                ('overhead_rate', models.DecimalField(decimal_places=2, default=0, help_text='직접노무비 대비 간접비 비율', max_digits=5, verbose_name='간접비 배부율(%)')),
                ('overhead_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준간접비')),
                ('total_standard_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준원가 합계')),
                ('is_current', models.BooleanField(default=True, verbose_name='현행 여부')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': 'historical 표준원가',
                'verbose_name_plural': 'historical 표준원가',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StandardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('effective_date', models.DateField(verbose_name='적용일')),
                ('material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준자재원가')),
                ('direct_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='직접노무시간')),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='시간당 노무비')),
                ('labor_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준노무비')),
                ('overhead_rate', models.DecimalField(decimal_places=2, default=0, help_text='직접노무비 대비 간접비 비율', max_digits=5, verbose_name='간접비 배부율(%)')),
                ('overhead_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준간접비')),
                ('total_standard_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='표준원가 합계')),
                ('is_current', models.BooleanField(default=True, verbose_name='현행 여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='inventory.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '표준원가',
                'verbose_name_plural': '표준원가',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('product', 'version'), name='uq_stdcost_product_version')],
            },
        ),
    ]
