# Generated by Django 5.2.12 on 2026-04-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_historicalproduct_serial_prefix_and_more'),
        ('production', '0014_historicalproductionrecord_actual_labor_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type__in': ['FINISHED', 'SEMI']}, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product', verbose_name='완제품'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'product_type__in': ['FINISHED', 'SEMI']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='완제품'),
        ),
    ]
