# Generated by Django 5.2.12 on 2026-04-10 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_bom_product_alter_historicalbom_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalqualityinspection',
            name='conditional_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='조건부합격 승인일시'),
        ),
        migrations.AddField(
            model_name='historicalqualityinspection',
            name='conditional_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='조건부합격 승인자'),
        ),
        migrations.AddField(
            model_name='historicalqualityinspection',
            name='conditional_notes',
            field=models.TextField(blank=True, verbose_name='조건부합격 사유'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='conditional_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='조건부합격 승인일시'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='conditional_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_approvals', to=settings.AUTH_USER_MODEL, verbose_name='조건부합격 승인자'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='conditional_notes',
            field=models.TextField(blank=True, verbose_name='조건부합격 사유'),
        ),
    ]
