# Generated by Django 5.2.12 on 2026-04-11 03:29

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_historicalqualityinspection_conditional_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkCenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='작업장명')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='코드')),
                ('capacity_per_day', models.PositiveIntegerField(default=100, verbose_name='일일생산능력')),
                ('efficiency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('2.00'))], verbose_name='효율')),
                ('operating_hours', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='가동시간')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 작업장',
                'verbose_name_plural': 'historical 작업장',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='작업장명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('capacity_per_day', models.PositiveIntegerField(default=100, verbose_name='일일생산능력')),
                ('efficiency_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('2.00'))], verbose_name='효율')),
                ('operating_hours', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('24.0'))], verbose_name='가동시간')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '작업장',
                'verbose_name_plural': '작업장',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductionSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('scheduled_start', models.DateTimeField(verbose_name='예정시작')),
                ('scheduled_end', models.DateTimeField(verbose_name='예정종료')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='실제시작')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='실제종료')),
                ('status', models.CharField(choices=[('PLANNED', '계획'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('DELAYED', '지연')], default='PLANNED', max_length=20, verbose_name='상태')),
                ('assigned_workers', models.PositiveIntegerField(default=1, verbose_name='배정인원')),
                ('priority', models.PositiveIntegerField(default=5, help_text='1(최우선) ~ 10(최하위)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='우선순위')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.workorder', verbose_name='작업지시')),
                ('work_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.workcenter', verbose_name='작업장')),
            ],
            options={
                'verbose_name': 'historical 생산스케줄',
                'verbose_name_plural': 'historical 생산스케줄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='work_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.workcenter', verbose_name='작업장'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='production.workcenter', verbose_name='작업장'),
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('scheduled_start', models.DateTimeField(verbose_name='예정시작')),
                ('scheduled_end', models.DateTimeField(verbose_name='예정종료')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='실제시작')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='실제종료')),
                ('status', models.CharField(choices=[('PLANNED', '계획'), ('IN_PROGRESS', '진행중'), ('COMPLETED', '완료'), ('DELAYED', '지연')], default='PLANNED', max_length=20, verbose_name='상태')),
                ('assigned_workers', models.PositiveIntegerField(default=1, verbose_name='배정인원')),
                ('priority', models.PositiveIntegerField(default=5, help_text='1(최우선) ~ 10(최하위)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='우선순위')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='production.workorder', verbose_name='작업지시')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='production.workcenter', verbose_name='작업장')),
            ],
            options={
                'verbose_name': '생산스케줄',
                'verbose_name_plural': '생산스케줄',
                'ordering': ['scheduled_start', 'priority'],
                'indexes': [models.Index(fields=['status'], name='idx_schedule_status'), models.Index(fields=['scheduled_start'], name='idx_schedule_start')],
            },
        ),
    ]
