# Generated by Django 5.2.12 on 2026-04-18 05:02

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_product_auto_standard_cost'),
        ('production', '0018_qualityinspection_idx_qc_result_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductionBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='형식: {WC.code}-{YYYYMMDD}-{SHIFT}-{SEQ:03d}', max_length=50, verbose_name='배치번호')),
                ('production_date', models.DateField(db_index=True, verbose_name='생산일')),
                ('shift', models.CharField(blank=True, choices=[('A', 'A조'), ('B', 'B조'), ('C', 'C조')], max_length=10, verbose_name='시프트')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='순번')),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='총수량')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='잔여수량')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('production_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionrecord', verbose_name='생산실적')),
                ('work_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.workcenter', verbose_name='작업장')),
            ],
            options={
                'verbose_name': 'historical 생산배치',
                'verbose_name_plural': 'historical 생산배치',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='형식: {WC.code}-{YYYYMMDD}-{SHIFT}-{SEQ:03d}', max_length=50, unique=True, verbose_name='배치번호')),
                ('production_date', models.DateField(db_index=True, verbose_name='생산일')),
                ('shift', models.CharField(blank=True, choices=[('A', 'A조'), ('B', 'B조'), ('C', 'C조')], max_length=10, verbose_name='시프트')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='순번')),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='총수량')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='잔여수량')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='inventory.product', verbose_name='제품')),
                ('production_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='production.productionrecord', verbose_name='생산실적')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.workcenter', verbose_name='작업장')),
            ],
            options={
                'verbose_name': '생산배치',
                'verbose_name_plural': '생산배치',
                'ordering': ['-production_date', '-sequence'],
                'indexes': [models.Index(fields=['work_center', 'production_date'], name='idx_batch_wc_date'), models.Index(fields=['product', 'production_date'], name='idx_batch_product_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='batch_remaining_non_negative')],
            },
        ),
    ]
