# Generated by Django 6.0.3 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="총합계(세포함)",
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="tax_total",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="부가세 합계"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="총합계(세포함)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_total",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="부가세 합계"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="부가세"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_with_tax",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="합계(세포함)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="공급가액"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="공급가액"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="공급가액"
            ),
        ),
    ]
