# Generated by Django 5.2.12 on 2026-03-19 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_historicalorderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquotationitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
    ]
