# Generated by Django 5.2.12 on 2026-03-19 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_historicalorderitem_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type'], name='idx_partner_type'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='idx_quotation_status'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quote_date'], name='idx_quotation_date'),
        ),
    ]
