# Generated by Django 5.2.12 on 2026-03-20 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_partner_idx_partner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인율(%)'),
        ),
        migrations.AddField(
            model_name='historicalquotationitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='historicalquotationitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인율(%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인율(%)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='할인율(%)'),
        ),
    ]
