# Generated by Django 5.2.12 on 2026-03-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_customer_options_remove_customer_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='order_type',
            field=models.CharField(choices=[('NORMAL', '일반주문'), ('SAMPLE', '샘플주문'), ('RETURN', '반품주문'), ('EXCHANGE', '교환주문')], default='NORMAL', max_length=10, verbose_name='주문유형'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='배송방법'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='운송장번호'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('NORMAL', '일반주문'), ('SAMPLE', '샘플주문'), ('RETURN', '반품주문'), ('EXCHANGE', '교환주문')], default='NORMAL', max_length=10, verbose_name='주문유형'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='배송방법'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='운송장번호'),
        ),
    ]
