# Generated by Django 5.2.12 on 2026-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_historicalorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='shipping_type',
            field=models.CharField(choices=[('PARCEL', '택배'), ('FREIGHT', '화물'), ('QUICK', '퀵서비스'), ('DIRECT', '직접배송'), ('PICKUP', '직접수령'), ('ETC', '기타')], default='PARCEL', max_length=10, verbose_name='배송유형'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_type',
            field=models.CharField(choices=[('PARCEL', '택배'), ('FREIGHT', '화물'), ('QUICK', '퀵서비스'), ('DIRECT', '직접배송'), ('PICKUP', '직접수령'), ('ETC', '기타')], default='PARCEL', max_length=10, verbose_name='배송유형'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='carrier',
            field=models.CharField(blank=True, choices=[('CJ', 'CJ대한통운'), ('HANJIN', '한진택배'), ('LOTTE', '롯데택배'), ('LOGEN', '로젠택배'), ('POST', '우체국택배'), ('ETC', '기타')], default='CJ', max_length=20, verbose_name='택배사'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, choices=[('CJ', 'CJ대한통운'), ('HANJIN', '한진택배'), ('LOTTE', '롯데택배'), ('LOGEN', '로젠택배'), ('POST', '우체국택배'), ('ETC', '기타')], default='CJ', max_length=20, verbose_name='택배사'),
        ),
    ]
