# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_historicalshipment_shipping_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='quote_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='견적번호'),
        ),
        migrations.AlterField(
            model_name='historicalshipment',
            name='shipment_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='배송번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='견적번호'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='배송번호'),
        ),
    ]
