# Generated by Django 5.2.12 on 2026-03-22 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_number_convert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_number'], 'verbose_name': '주문', 'verbose_name_plural': '주문'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-quote_number'], 'verbose_name': '견적서', 'verbose_name_plural': '견적서'},
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산원가 (견적서에서 자동 반영)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가'),
        ),
        migrations.AddField(
            model_name='historicalquotationitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산원가 (자동 반영)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산원가 (견적서에서 자동 반영)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='생산원가 (자동 반영)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='원가'),
        ),
        migrations.AlterField(
            model_name='historicalquotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급단가'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급단가'),
        ),
    ]
