# Generated by Django 5.2.12 on 2026-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_order_options_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='입금완료'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='입금일'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='입금완료'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='입금일'),
        ),
    ]
