# Generated by Django 5.2.12 on 2026-03-22 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_historicalorder_is_paid_historicalorder_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='배송비'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='배송비'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
    ]
