# Generated by Django 5.2.12 on 2026-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_historicalorder_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquotation',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
    ]
