# Generated by Django 5.2.12 on 2026-03-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_costsettlement_options_and_more'),
        ('sales', '0019_historicalquotation_vat_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='입금계좌'),
        ),
        migrations.AddField(
            model_name='historicalquotation',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='입금계좌'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounting.bankaccount', verbose_name='입금계좌'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='accounting.bankaccount', verbose_name='입금계좌'),
        ),
    ]
