# Generated by Django 5.2.12 on 2026-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_historicalorder_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='정산완료'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='정산완료'),
        ),
    ]
