# Generated by Django 5.2.12 on 2026-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_historicalorder_is_settled_order_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='플랫폼 수수료율. 입금 시 자동 차감에 사용됩니다.', max_digits=5, verbose_name='기본 수수료율(%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='플랫폼 수수료율. 입금 시 자동 차감에 사용됩니다.', max_digits=5, verbose_name='기본 수수료율(%)'),
        ),
    ]
