# Generated by Django 5.2.12 on 2026-03-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_historicalpartner_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrate',
            options={'verbose_name': '수수료 항목', 'verbose_name_plural': '수수료 항목'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommissionrate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 수수료 항목', 'verbose_name_plural': 'historical 수수료 항목'},
        ),
        migrations.AlterUniqueTogether(
            name='commissionrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='calc_type',
            field=models.CharField(choices=[('PERCENT', '정률(%)'), ('FIXED', '정액(원)')], default='PERCENT', max_length=10, verbose_name='계산방식'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정액(원) 방식일 때 적용', max_digits=15, verbose_name='고정금액(원)'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='name',
            field=models.CharField(default='기본 수수료', help_text='예: 판매수수료, 결제수수료, 배송대행비 등', max_length=100, verbose_name='항목명'),
        ),
        migrations.AddField(
            model_name='historicalcommissionrate',
            name='calc_type',
            field=models.CharField(choices=[('PERCENT', '정률(%)'), ('FIXED', '정액(원)')], default='PERCENT', max_length=10, verbose_name='계산방식'),
        ),
        migrations.AddField(
            model_name='historicalcommissionrate',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정액(원) 방식일 때 적용', max_digits=15, verbose_name='고정금액(원)'),
        ),
        migrations.AddField(
            model_name='historicalcommissionrate',
            name='name',
            field=models.CharField(default='기본 수수료', help_text='예: 판매수수료, 결제수수료, 배송대행비 등', max_length=100, verbose_name='항목명'),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='정률(%) 방식일 때 적용', max_digits=6, verbose_name='수수료율(%)'),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='수수료율(%)'),
        ),
        migrations.AlterField(
            model_name='historicalcommissionrate',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='정률(%) 방식일 때 적용', max_digits=6, verbose_name='수수료율(%)'),
        ),
        migrations.AlterField(
            model_name='historicalcommissionrecord',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='수수료율(%)'),
        ),
    ]
