# Generated by Django 5.2.12 on 2026-03-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_commissionrate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartner',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='commission_rate',
        ),
    ]
