# Generated by Django 5.2.12 on 2026-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_remove_historicalpartner_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrate',
            options={'ordering': ['partner', 'name'], 'verbose_name': '수수료 항목', 'verbose_name_plural': '수수료 항목'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk'], 'verbose_name': '주문항목', 'verbose_name_plural': '주문항목'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['pk'], 'verbose_name': '견적항목', 'verbose_name_plural': '견적항목'},
        ),
    ]
