# Generated by Django 5.2.12 on 2026-03-23 04:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_commissionrate_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='출고수량'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='출고수량'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('CONFIRMED', '확정'), ('PARTIAL_SHIPPED', '부분출고'), ('SHIPPED', '출고완료'), ('DELIVERED', '배송완료'), ('CANCELLED', '취소')], default='DRAFT', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('CONFIRMED', '확정'), ('PARTIAL_SHIPPED', '부분출고'), ('SHIPPED', '출고완료'), ('DELIVERED', '배송완료'), ('CANCELLED', '취소')], default='DRAFT', max_length=20, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='HistoricalShipmentItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('quantity', models.PositiveIntegerField(verbose_name='출고수량')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.orderitem', verbose_name='주문항목')),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.shipment', verbose_name='배송')),
            ],
            options={
                'verbose_name': 'historical 배송항목',
                'verbose_name_plural': 'historical 배송항목',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('quantity', models.PositiveIntegerField(verbose_name='출고수량')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='sales.orderitem', verbose_name='주문항목')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.shipment', verbose_name='배송')),
            ],
            options={
                'verbose_name': '배송항목',
                'verbose_name_plural': '배송항목',
                'ordering': ['pk'],
            },
        ),
    ]
