# Generated by Django 5.2.12 on 2026-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_historicalorderitem_shipped_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='평균 납품 소요일', verbose_name='리드타임(일)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='평균 납품 소요일', verbose_name='리드타임(일)'),
        ),
    ]
