# Generated by Django 5.2.12 on 2026-03-23 13:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_currency_historicalcurrency_historicalexchangerate_and_more'),
        ('sales', '0028_historicalpartner_lead_time_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency', verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='적용환율'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='default_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency', verbose_name='기본통화'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency', verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='적용환율'),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency', verbose_name='기본통화'),
        ),
        migrations.CreateModel(
            name='HistoricalShipmentTracking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('status', models.CharField(max_length=50, verbose_name='상태')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='위치')),
                ('description', models.TextField(blank=True, verbose_name='상세')),
                ('tracked_at', models.DateTimeField(verbose_name='추적시각')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.shipment', verbose_name='배송')),
            ],
            options={
                'verbose_name': 'historical 배송추적',
                'verbose_name_plural': 'historical 배송추적',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShippingCarrier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='택배사코드')),
                ('name', models.CharField(max_length=50, verbose_name='택배사명')),
                ('tracking_url_template', models.URLField(blank=True, help_text='{tracking_number}를 치환', verbose_name='추적URL 템플릿')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API 엔드포인트')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본택배사')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 택배사',
                'verbose_name_plural': 'historical 택배사',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('status', models.CharField(max_length=50, verbose_name='상태')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='위치')),
                ('description', models.TextField(blank=True, verbose_name='상세')),
                ('tracked_at', models.DateTimeField(verbose_name='추적시각')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_history', to='sales.shipment', verbose_name='배송')),
            ],
            options={
                'verbose_name': '배송추적',
                'verbose_name_plural': '배송추적',
                'ordering': ['-tracked_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='택배사코드')),
                ('name', models.CharField(max_length=50, verbose_name='택배사명')),
                ('tracking_url_template', models.URLField(blank=True, help_text='{tracking_number}를 치환', verbose_name='추적URL 템플릿')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API 엔드포인트')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본택배사')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '택배사',
                'verbose_name_plural': '택배사',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='shipping_carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.shippingcarrier', verbose_name='택배사(상세)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='sales.shippingcarrier', verbose_name='택배사(상세)'),
        ),
    ]
