# Generated by Django 5.2.12 on 2026-03-24 01:31

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0029_historicalorder_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalshippingcarrier",
            name="api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API Key"
            ),
        ),
        migrations.AlterField(
            model_name="shippingcarrier",
            name="api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API Key"
            ),
        ),
    ]
