# Generated by Django 5.2.12 on 2026-03-24 02:02

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0030_alter_historicalshippingcarrier_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="shipping_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpartner",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="historicalpartner",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpartner",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="historicalshipment",
            name="receiver_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="historicalshipment",
            name="receiver_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="수취인연락처"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="receiver_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="receiver_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="수취인연락처"
            ),
        ),
    ]
