# Generated by Django 5.2.12 on 2026-03-27 02:07

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='bank_account',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='bank_holder',
            field=models.CharField(blank=True, max_length=50, verbose_name='예금주'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_account',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_holder',
            field=models.CharField(blank=True, max_length=50, verbose_name='예금주'),
        ),
        migrations.AddField(
            model_name='partner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='은행명'),
        ),
    ]
