# Generated by Django 5.2.12 on 2026-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_historicalpartner_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='고객코드'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='고객코드'),
        ),
    ]
