# Generated by Django 5.2.12 on 2026-03-29 03:42

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_historicalproduct_code_alter_product_code_and_more'),
        ('sales', '0034_alter_customer_code_alter_historicalcustomer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='최소수량')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, help_text='설정 시 이 단가 적용. 비워두면 기본 판매단가에서 할인', max_digits=15, null=True, verbose_name='적용단가')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='할인율(%)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='적용시작일')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='적용종료일')),
                ('priority', models.PositiveIntegerField(default=0, help_text='높을수록 우선 적용', verbose_name='우선순위')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='고객')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='거래처')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': 'historical 가격규칙',
                'verbose_name_plural': 'historical 가격규칙',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='최소수량')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, help_text='설정 시 이 단가 적용. 비워두면 기본 판매단가에서 할인', max_digits=15, null=True, verbose_name='적용단가')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='할인율(%)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='적용시작일')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='적용종료일')),
                ('priority', models.PositiveIntegerField(default=0, help_text='높을수록 우선 적용', verbose_name='우선순위')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='sales.customer', verbose_name='고객')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rules', to='sales.partner', verbose_name='거래처')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='inventory.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '가격규칙',
                'verbose_name_plural': '가격규칙',
                'ordering': ['-priority', 'min_quantity'],
                'constraints': [models.UniqueConstraint(fields=('product', 'partner', 'customer', 'min_quantity'), name='uq_price_rule')],
            },
        ),
    ]
