# Generated by Django 5.2.12 on 2026-03-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_bankaccount_show_on_dashboard_and_more'),
        ('sales', '0035_historicalpricerule_pricerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='수수료 자동 차감 계좌 (미설정 시 기본계좌)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='수수료 계좌'),
        ),
        migrations.AddField(
            model_name='partner',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, help_text='수수료 자동 차감 계좌 (미설정 시 기본계좌)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_partners', to='accounting.bankaccount', verbose_name='수수료 계좌'),
        ),
    ]
