# Generated by Django 5.2.12 on 2026-03-30 08:07

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_historicalpartner_commission_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='도로명주소'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='도로명주소'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='배송 상세주소'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='배송 도로명주소'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='도로명주소'),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='receiver_address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='수취인 상세주소'),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='receiver_address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='수취인 도로명주소'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='배송 상세주소'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='배송 도로명주소'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='도로명주소'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_address_detail',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='수취인 상세주소'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_address_road',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='수취인 도로명주소'),
        ),
    ]
