# Generated by Django 5.2.12 on 2026-04-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_customer_address_detail_customer_address_road_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='store_module',
            field=models.CharField(blank=True, default='', help_text='연결된 스토어 모듈 ID (예: naver_smartstore, coupang, direct_sale)', max_length=50, verbose_name='스토어 모듈'),
        ),
        migrations.AddField(
            model_name='partner',
            name='store_module',
            field=models.CharField(blank=True, default='', help_text='연결된 스토어 모듈 ID (예: naver_smartstore, coupang, direct_sale)', max_length=50, verbose_name='스토어 모듈'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('CONFIRMED', '확정'), ('PARTIAL_SHIPPED', '부분출고'), ('SHIPPED', '출고완료'), ('DELIVERED', '배송완료'), ('CLOSED', '종결'), ('CANCELLED', '취소')], default='DRAFT', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('CONFIRMED', '확정'), ('PARTIAL_SHIPPED', '부분출고'), ('SHIPPED', '출고완료'), ('DELIVERED', '배송완료'), ('CLOSED', '종결'), ('CANCELLED', '취소')], default='DRAFT', max_length=20, verbose_name='상태'),
        ),
    ]
