# Generated by Django 5.2.12 on 2026-04-01 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_historicalsalessettlement_total_cost_variance_and_more'),
        ('sales', '0038_historicalpartner_store_module_partner_store_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='주문 생성 시 자동 설정되는 입금계좌', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='기본 입금계좌'),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, help_text='주문 생성 시 자동 설정되는 입금계좌', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_partners', to='accounting.bankaccount', verbose_name='기본 입금계좌'),
        ),
    ]
