# Generated by Django 5.2.12 on 2026-04-01 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_historicalsalessettlement_total_cost_variance_and_more'),
        ('sales', '0040_backfill_order_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartner',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='고객: 입금계좌 / 공급처: 출금계좌', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='기본 거래계좌'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, help_text='고객: 입금계좌 / 공급처: 출금계좌', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_partners', to='accounting.bankaccount', verbose_name='기본 거래계좌'),
        ),
    ]
