# Generated by Django 5.2.12 on 2026-04-02 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_alter_historicalpartner_default_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼(네이버, 쿠팡 등)에서 공제한 수수료', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='플랫폼 수수료'),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼(네이버, 쿠팡 등)에서 공제한 수수료', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='플랫폼 수수료'),
        ),
    ]
