# Generated by Django 5.2.12 on 2026-04-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_add_platform_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrate',
            name='base_type',
            field=models.CharField(choices=[('SUPPLY', '공급가액(VAT 제외)'), ('TOTAL', '판매가(VAT 포함)')], default='SUPPLY', help_text='정률 수수료의 기준금액 (공급가액 or 판매가)', max_length=10, verbose_name='계산기준'),
        ),
        migrations.AddField(
            model_name='historicalcommissionrate',
            name='base_type',
            field=models.CharField(choices=[('SUPPLY', '공급가액(VAT 제외)'), ('TOTAL', '판매가(VAT 포함)')], default='SUPPLY', help_text='정률 수수료의 기준금액 (공급가액 or 판매가)', max_length=10, verbose_name='계산기준'),
        ),
    ]
