# Generated by Django 5.2.12 on 2026-04-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_add_commission_base_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='original_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.order', verbose_name='원본주문'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='return_reason',
            field=models.TextField(blank=True, default='', verbose_name='반품/교환 사유'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='sales.order', verbose_name='원본주문'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, default='', verbose_name='반품/교환 사유'),
        ),
    ]
