# Generated by Django 5.2.12 on 2026-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_historicalorder_original_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', '승인대기'), ('APPROVED', '승인'), ('SUSPENDED', '정지'), ('REJECTED', '거절')], default='APPROVED', max_length=20, verbose_name='승인상태'),
        ),
        migrations.AddField(
            model_name='partner',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', '승인대기'), ('APPROVED', '승인'), ('SUSPENDED', '정지'), ('REJECTED', '거절')], default='APPROVED', max_length=20, verbose_name='승인상태'),
        ),
    ]
