# Generated by Django 5.2.12 on 2026-04-23 01:39

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def backfill_shipping_charged(apps, schema_editor):
    Order = apps.get_model('sales', 'Order')
    Order.objects.update(shipping_charged=F('shipping_cost'))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_charged',
            field=models.DecimalField(decimal_places=0, default=0, help_text='고객에게 청구한 배송비(현금영수증/세금계산서 기준)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='청구 배송비'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charged',
            field=models.DecimalField(decimal_places=0, default=0, help_text='고객에게 청구한 배송비(현금영수증/세금계산서 기준)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='청구 배송비'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='실제 지급한 배송비(정산용)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='실제 배송비'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='실제 지급한 배송비(정산용)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='실제 배송비'),
        ),
        migrations.RunPython(backfill_shipping_charged, migrations.RunPython.noop),
    ]
