# Generated by Django 5.2.12 on 2026-04-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_order_shipping_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_method',
            field=models.CharField(choices=[('CARD', '신용카드'), ('BANK_TRANSFER', '계좌이체'), ('CASH', '현금'), ('VIRTUAL_ACCOUNT', '가상계좌'), ('NAVER_PAY', '네이버페이'), ('KAKAO_PAY', '카카오페이'), ('PLATFORM', '플랫폼정산'), ('OTHER', '기타')], default='CARD', max_length=32, verbose_name='결제수단'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='sales_channel',
            field=models.CharField(choices=[('DIRECT', '자사몰'), ('NAVER', '네이버 스마트스토어'), ('COUPANG', '쿠팡'), ('OFFLINE', '오프라인'), ('PHONE', '전화/카카오'), ('OTHER', '기타')], default='DIRECT', max_length=32, verbose_name='판매채널'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='tax_type',
            field=models.CharField(choices=[('TAXABLE', '과세'), ('ZERO_RATE', '영세율(수출)'), ('EXEMPT', '면세')], default='TAXABLE', max_length=16, verbose_name='과세구분'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='actual_cogs',
            field=models.DecimalField(decimal_places=0, default=0, help_text='StockLot 소진 기반 FIFO/LIFO 실제 원가 (시그널 자동 갱신)', max_digits=15, verbose_name='실제매출원가'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', '신용카드'), ('BANK_TRANSFER', '계좌이체'), ('CASH', '현금'), ('VIRTUAL_ACCOUNT', '가상계좌'), ('NAVER_PAY', '네이버페이'), ('KAKAO_PAY', '카카오페이'), ('PLATFORM', '플랫폼정산'), ('OTHER', '기타')], default='CARD', max_length=32, verbose_name='결제수단'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('DIRECT', '자사몰'), ('NAVER', '네이버 스마트스토어'), ('COUPANG', '쿠팡'), ('OFFLINE', '오프라인'), ('PHONE', '전화/카카오'), ('OTHER', '기타')], default='DIRECT', max_length=32, verbose_name='판매채널'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_type',
            field=models.CharField(choices=[('TAXABLE', '과세'), ('ZERO_RATE', '영세율(수출)'), ('EXEMPT', '면세')], default='TAXABLE', max_length=16, verbose_name='과세구분'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='actual_cogs',
            field=models.DecimalField(decimal_places=0, default=0, help_text='StockLot 소진 기반 FIFO/LIFO 실제 원가 (시그널 자동 갱신)', max_digits=15, verbose_name='실제매출원가'),
        ),
    ]
