# Generated by Django 5.2.12 on 2026-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_add_baddebtallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='accounting_date',
            field=models.DateField(blank=True, help_text='매출/세금계산서 귀속월 — 공란 시 order_date 사용. 플랫폼 정산일과 카드 승인일 차이가 있을 때 회계 기간 분리용.', null=True, verbose_name='회계인식일'),
        ),
        migrations.AddField(
            model_name='order',
            name='accounting_date',
            field=models.DateField(blank=True, help_text='매출/세금계산서 귀속월 — 공란 시 order_date 사용. 플랫폼 정산일과 카드 승인일 차이가 있을 때 회계 기간 분리용.', null=True, verbose_name='회계인식일'),
        ),
    ]
