# Generated by Django 5.2.12 on 2026-04-25 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_historicalorder_accounting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='progress_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='진행기준 수익인식 시 누적 진행률 (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='진행률(%)'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='revenue_recognition_method',
            field=models.CharField(choices=[('DELIVERY', '인도기준 (출고시 100%)'), ('PROGRESS', '진행기준 (진행률에 따라 분할)'), ('COMPLETION', '완성기준 (CLOSED 시 100%)')], default='DELIVERY', help_text='K-IFRS 1115호 — 진행기준 시 progress_rate 활용', max_length=16, verbose_name='수익인식방법'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='entity_type',
            field=models.CharField(choices=[('BUSINESS', '사업자'), ('INDIVIDUAL', '개인'), ('FOREIGN', '외국인/해외법인')], default='BUSINESS', help_text='증빙 발행시 사업자/개인 분기 — 세금계산서 vs 현금영수증', max_length=12, verbose_name='주체구분'),
        ),
        migrations.AddField(
            model_name='order',
            name='progress_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='진행기준 수익인식 시 누적 진행률 (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='진행률(%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='revenue_recognition_method',
            field=models.CharField(choices=[('DELIVERY', '인도기준 (출고시 100%)'), ('PROGRESS', '진행기준 (진행률에 따라 분할)'), ('COMPLETION', '완성기준 (CLOSED 시 100%)')], default='DELIVERY', help_text='K-IFRS 1115호 — 진행기준 시 progress_rate 활용', max_length=16, verbose_name='수익인식방법'),
        ),
        migrations.AddField(
            model_name='partner',
            name='entity_type',
            field=models.CharField(choices=[('BUSINESS', '사업자'), ('INDIVIDUAL', '개인'), ('FOREIGN', '외국인/해외법인')], default='BUSINESS', help_text='증빙 발행시 사업자/개인 분기 — 세금계산서 vs 현금영수증', max_length=12, verbose_name='주체구분'),
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='business_number',
            field=models.CharField(blank=True, help_text='entity_type=BUSINESS 시 필수 (123-45-67890 형식)', max_length=20, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='business_number',
            field=models.CharField(blank=True, help_text='entity_type=BUSINESS 시 필수 (123-45-67890 형식)', max_length=20, verbose_name='사업자번호'),
        ),
    ]
