# Generated by Django 5.2.12 on 2026-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_historicalorder_progress_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='default_payment_method',
            field=models.CharField(blank=True, default='', help_text='이 거래처로 주문 생성 시 자동 채워질 결제수단 (Order.PaymentMethod 값)', max_length=32, verbose_name='기본 결제수단'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='default_sales_channel',
            field=models.CharField(blank=True, default='', help_text='이 거래처로 주문 생성 시 자동 채워질 판매채널 (Order.SalesChannel 값)', max_length=32, verbose_name='기본 판매채널'),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_payment_method',
            field=models.CharField(blank=True, default='', help_text='이 거래처로 주문 생성 시 자동 채워질 결제수단 (Order.PaymentMethod 값)', max_length=32, verbose_name='기본 결제수단'),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_sales_channel',
            field=models.CharField(blank=True, default='', help_text='이 거래처로 주문 생성 시 자동 채워질 판매채널 (Order.SalesChannel 값)', max_length=32, verbose_name='기본 판매채널'),
        ),
    ]
