# Generated by Django 5.2.12 on 2026-04-28 05:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_historicalpartner_default_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='결제수단 코드')),
                ('name', models.CharField(max_length=100, verbose_name='결제수단명')),
                ('is_card', models.BooleanField(default=False, help_text='True 시 PG가 국세청에 자동 신고 (카드매출전표)', verbose_name='카드 결제 여부')),
                ('is_cash_equivalent', models.BooleanField(default=False, help_text='현금영수증 발행 가능 여부 판단용', verbose_name='현금성 여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 결제수단',
                'verbose_name_plural': 'historical 결제수단',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesChannel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='채널 코드')),
                ('name', models.CharField(max_length=100, verbose_name='채널명')),
                ('is_marketplace', models.BooleanField(default=False, help_text='True 시 PlatformFinancialConfig 와 연동 가능', verbose_name='마켓플레이스 여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 판매채널',
                'verbose_name_plural': 'historical 판매채널',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='결제수단 코드')),
                ('name', models.CharField(max_length=100, verbose_name='결제수단명')),
                ('is_card', models.BooleanField(default=False, help_text='True 시 PG가 국세청에 자동 신고 (카드매출전표)', verbose_name='카드 결제 여부')),
                ('is_cash_equivalent', models.BooleanField(default=False, help_text='현금영수증 발행 가능 여부 판단용', verbose_name='현금성 여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '결제수단',
                'verbose_name_plural': '결제수단',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='채널 코드')),
                ('name', models.CharField(max_length=100, verbose_name='채널명')),
                ('is_marketplace', models.BooleanField(default=False, help_text='True 시 PlatformFinancialConfig 와 연동 가능', verbose_name='마켓플레이스 여부')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='정렬순서')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '판매채널',
                'verbose_name_plural': '판매채널',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
