# Generated by Django 5.2.12 on 2026-04-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0002_seed_kr_country'),
        ('sales', '0052_historicalpaymentmethod_historicalsaleschannel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='거래처 소속 국가 (다국가 모드용 — 미설정 시 활성 국가 적용)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, help_text='거래처 소속 국가 (다국가 모드용 — 미설정 시 활성 국가 적용)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
    ]
