# Generated by Django 5.2.12 on 2026-04-30 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_backfill_partner_country_kr'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleslead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막접촉일'),
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='연결거래처'),
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='won_date',
            field=models.DateField(blank=True, null=True, verbose_name='수주일'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막접촉일'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to='sales.partner', verbose_name='연결거래처'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='won_date',
            field=models.DateField(blank=True, null=True, verbose_name='수주일'),
        ),
    ]
