# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        ('plm', '0001_initial'),
        ('production', '0017_historicalworkcenter_workcenter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomrevision',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='production.bom', verbose_name='BOM'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawings', to='inventory.product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='ecnitem',
            name='ecn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='plm.engineeringchangenotice', verbose_name='ECN'),
        ),
        migrations.AlterField(
            model_name='ecnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecn_items', to='inventory.product', verbose_name='대상품목'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='inventory.product', verbose_name='제품'),
        ),
    ]
