# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_serialnumber_idx_serial_status_date_and_more'),
        ('plm', '0002_alter_bomrevision_bom_alter_drawing_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engineeringchangenotice',
            index=models.Index(fields=['status', 'created_at'], name='idx_ecn_status_date'),
        ),
        migrations.AddIndex(
            model_name='engineeringchangenotice',
            index=models.Index(fields=['priority', 'status'], name='idx_ecn_priority_status'),
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['status', 'created_at'], name='idx_pv_status_date'),
        ),
    ]
