# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdowntime',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='cmms.equipment', verbose_name='설비'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='cmms.equipment', verbose_name='설비'),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='cmms.equipment', verbose_name='설비'),
        ),
    ]
