# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_alter_equipmentdowntime_equipment_and_more'),
        ('hr', '0013_employeeprofile_idx_emp_dept_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'is_active'], name='idx_equip_status_active'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['equipment', 'start_time'], name='idx_dt_equip_time'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['equipment', 'next_due'], name='idx_ms_equip_due'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['next_due'], name='idx_ms_next_due'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['status', 'created_at'], name='idx_mwo_status_date'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['equipment', 'status'], name='idx_mwo_equip_status'),
        ),
    ]
