# Generated by Django 5.2.12 on 2026-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_idx_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='감사 증적 열람 권한 (ISMS/회계 증빙 접근)', verbose_name='감사권한'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='감사 증적 열람 권한 (ISMS/회계 증빙 접근)', verbose_name='감사권한'),
        ),
    ]
