# Generated by Django 5.2.12 on 2026-04-01 23:58

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_permissions_and_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='연락처'),
        ),
    ]
