# Generated by Django 5.2.12 on 2026-04-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationschedule',
            options={'ordering': ['-updated_at'], 'verbose_name': '자동화스케줄', 'verbose_name_plural': '자동화스케줄'},
        ),
    ]
