# Generated by Django 5.2.12 on 2026-04-30 02:36

import apps.localizations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa', '0002_alter_automationschedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationschedule',
            name='timezone',
            field=models.CharField(default=apps.localizations.get_default_timezone, max_length=50, verbose_name='시간대'),
        ),
        migrations.AlterField(
            model_name='historicalautomationschedule',
            name='timezone',
            field=models.CharField(default=apps.localizations.get_default_timezone, max_length=50, verbose_name='시간대'),
        ),
    ]
