# Generated by Django 5.2.12 on 2026-03-18 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='idx_comment_post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', 'is_active'], name='idx_post_board_active'),
        ),
    ]
