# Generated by Django 6.0.3 on 2026-03-16 05:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInvestmentRound",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="라운드명")),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("SEED", "시드"),
                            ("PRE_A", "프리시리즈A"),
                            ("SERIES_A", "시리즈A"),
                            ("SERIES_B", "시리즈B"),
                            ("SERIES_C", "시리즈C"),
                            ("BRIDGE", "브릿지"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="라운드유형",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="목표금액",
                    ),
                ),
                (
                    "raised_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="모집금액",
                    ),
                ),
                ("round_date", models.DateField(verbose_name="투자일")),
                (
                    "pre_valuation",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="투자전 기업가치",
                    ),
                ),
                (
                    "post_valuation",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="투자후 기업가치",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 투자라운드",
                "verbose_name_plural": "historical 투자라운드",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInvestor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="투자자명")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="소속회사"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="담당자"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                ("registration_date", models.DateField(verbose_name="등록일")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 투자자",
                "verbose_name_plural": "historical 투자자",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InvestmentRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="라운드명")),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("SEED", "시드"),
                            ("PRE_A", "프리시리즈A"),
                            ("SERIES_A", "시리즈A"),
                            ("SERIES_B", "시리즈B"),
                            ("SERIES_C", "시리즈C"),
                            ("BRIDGE", "브릿지"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="라운드유형",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="목표금액",
                    ),
                ),
                (
                    "raised_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="모집금액",
                    ),
                ),
                ("round_date", models.DateField(verbose_name="투자일")),
                (
                    "pre_valuation",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="투자전 기업가치",
                    ),
                ),
                (
                    "post_valuation",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="투자후 기업가치",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "투자라운드",
                "verbose_name_plural": "투자라운드",
                "ordering": ["-round_date"],
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="투자자명")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="소속회사"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="담당자"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                ("registration_date", models.DateField(verbose_name="등록일")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "투자자",
                "verbose_name_plural": "투자자",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalInvestment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="투자금액"
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="지분율(%)"
                    ),
                ),
                ("investment_date", models.DateField(verbose_name="투자일")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.investmentround",
                        verbose_name="투자라운드",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 투자내역",
                "verbose_name_plural": "historical 투자내역",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEquityChange",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("INVESTMENT", "신규투자"),
                            ("DILUTION", "희석"),
                            ("TRANSFER", "지분양도"),
                            ("BUYBACK", "자사주매입"),
                        ],
                        max_length=20,
                        verbose_name="변동유형",
                    ),
                ),
                ("change_date", models.DateField(verbose_name="변동일")),
                (
                    "before_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="변동전 지분율(%)"
                    ),
                ),
                (
                    "after_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="변동후 지분율(%)"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_round",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.investmentround",
                        verbose_name="관련라운드",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 지분변동",
                "verbose_name_plural": "historical 지분변동",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDistribution",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("DIVIDEND", "배당"),
                            ("PROFIT_SHARE", "수익분배"),
                            ("INTERIM", "중간배당"),
                        ],
                        max_length=20,
                        verbose_name="분배유형",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="분배금액"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="예정일")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="지급일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "예정"),
                            ("PENDING", "대기"),
                            ("PAID", "지급완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField(verbose_name="회계연도")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 배당/분배",
                "verbose_name_plural": "historical 배당/분배",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EquityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("INVESTMENT", "신규투자"),
                            ("DILUTION", "희석"),
                            ("TRANSFER", "지분양도"),
                            ("BUYBACK", "자사주매입"),
                        ],
                        max_length=20,
                        verbose_name="변동유형",
                    ),
                ),
                ("change_date", models.DateField(verbose_name="변동일")),
                (
                    "before_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="변동전 지분율(%)"
                    ),
                ),
                (
                    "after_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="변동후 지분율(%)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "related_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="investment.investmentround",
                        verbose_name="관련라운드",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equity_changes",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "지분변동",
                "verbose_name_plural": "지분변동",
                "ordering": ["-change_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("DIVIDEND", "배당"),
                            ("PROFIT_SHARE", "수익분배"),
                            ("INTERIM", "중간배당"),
                        ],
                        max_length=20,
                        verbose_name="분배유형",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="분배금액"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="예정일")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="지급일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "예정"),
                            ("PENDING", "대기"),
                            ("PAID", "지급완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField(verbose_name="회계연도")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributions",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "배당/분배",
                "verbose_name_plural": "배당/분배",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="투자금액"
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="지분율(%)"
                    ),
                ),
                ("investment_date", models.DateField(verbose_name="투자일")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="investment.investmentround",
                        verbose_name="투자라운드",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="investment.investor",
                        verbose_name="투자자",
                    ),
                ),
            ],
            options={
                "verbose_name": "투자내역",
                "verbose_name_plural": "투자내역",
                "ordering": ["-investment_date"],
                "unique_together": {("investor", "round")},
            },
        ),
    ]
