# Generated by Django 5.2.12 on 2026-04-13 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investor_round_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('investor', 'round'), name='uq_investment_investor_round'),
        ),
    ]
