# Generated by Django 5.2.12 on 2026-04-15 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['investor', 'status'], name='idx_dist_inv_status'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['fiscal_year', 'status'], name='idx_dist_yr_status'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['status', 'scheduled_date'], name='idx_dist_status_date'),
        ),
        migrations.AddIndex(
            model_name='equitychange',
            index=models.Index(fields=['investor', 'change_date'], name='idx_equity_inv_date'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor', 'investment_date'], name='idx_invest_inv_date'),
        ),
    ]
