# Generated by Django 5.2.12 on 2026-04-11 03:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInstalledModule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('module_id', models.CharField(db_index=True, max_length=100, verbose_name='모듈 ID')),
                ('name', models.CharField(max_length=200, verbose_name='모듈명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('category', models.CharField(choices=[('COMPLIANCE', '법규/컴플라이언스'), ('PRODUCTION', '생산'), ('PURCHASE', '구매'), ('SALES', '영업/CRM'), ('ACCOUNTING', '회계/재무'), ('HR', '인사/급여'), ('SYSTEM', '시스템')], max_length=50, verbose_name='카테고리')),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 코드. 빈 값은 범용 모듈.', max_length=10, verbose_name='국가코드')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='활성화')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='설정')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='버전')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='의존성')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 설치된 모듈',
                'verbose_name_plural': 'historical 설치된 모듈',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InstalledModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('module_id', models.CharField(max_length=100, unique=True, verbose_name='모듈 ID')),
                ('name', models.CharField(max_length=200, verbose_name='모듈명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('category', models.CharField(choices=[('COMPLIANCE', '법규/컴플라이언스'), ('PRODUCTION', '생산'), ('PURCHASE', '구매'), ('SALES', '영업/CRM'), ('ACCOUNTING', '회계/재무'), ('HR', '인사/급여'), ('SYSTEM', '시스템')], max_length=50, verbose_name='카테고리')),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 코드. 빈 값은 범용 모듈.', max_length=10, verbose_name='국가코드')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='활성화')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='설정')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='버전')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='의존성')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '설치된 모듈',
                'verbose_name_plural': '설치된 모듈',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
    ]
