# Generated by Django 5.2.12 on 2026-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstalledmodule',
            name='category',
            field=models.CharField(choices=[('COMPLIANCE', '법규/컴플라이언스'), ('PRODUCTION', '생산'), ('PURCHASE', '구매'), ('SALES', '영업/CRM'), ('ACCOUNTING', '회계/재무'), ('HR', '인사/급여'), ('GROUPWARE', '그룹웨어'), ('SYSTEM', '시스템')], max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='installedmodule',
            name='category',
            field=models.CharField(choices=[('COMPLIANCE', '법규/컴플라이언스'), ('PRODUCTION', '생산'), ('PURCHASE', '구매'), ('SALES', '영업/CRM'), ('ACCOUNTING', '회계/재무'), ('HR', '인사/급여'), ('GROUPWARE', '그룹웨어'), ('SYSTEM', '시스템')], max_length=50, verbose_name='카테고리'),
        ),
    ]
