# Generated by Django 6.0.3 on 2026-03-16 07:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0003_commissionrecord_historicalcommissionrate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMarketplaceConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="스토어명"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=200, verbose_name="Client ID"),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=200, verbose_name="Client Secret"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 스토어 설정",
                "verbose_name_plural": "historical 스토어 설정",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMarketplaceOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "store_order_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="스토어주문번호"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="상품명"),
                ),
                (
                    "option_name",
                    models.CharField(blank=True, max_length=200, verbose_name="옵션"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="수량")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="결제금액"
                    ),
                ),
                ("buyer_name", models.CharField(max_length=100, verbose_name="주문자")),
                (
                    "buyer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=100, verbose_name="수취인"),
                ),
                (
                    "receiver_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="수취인연락처"
                    ),
                ),
                (
                    "receiver_address",
                    models.TextField(blank=True, verbose_name="배송주소"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "신규주문"),
                            ("CONFIRMED", "확인"),
                            ("SHIPPED", "발송완료"),
                            ("DELIVERED", "배송완료"),
                            ("CANCELLED", "취소"),
                            ("RETURNED", "반품"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("ordered_at", models.DateTimeField(verbose_name="주문일시")),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="동기화일시"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "erp_order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sales.order",
                        verbose_name="연결된 ERP 주문",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 스토어주문",
                "verbose_name_plural": "historical 스토어주문",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSyncLog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "direction",
                    models.CharField(
                        choices=[("PULL", "수신"), ("PUSH", "발신")],
                        max_length=10,
                        verbose_name="방향",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="시작일시")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="전체건수"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="성공건수"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="오류건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류내용"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 동기화이력",
                "verbose_name_plural": "historical 동기화이력",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MarketplaceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="스토어명"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=200, verbose_name="Client ID"),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=200, verbose_name="Client Secret"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스토어 설정",
                "verbose_name_plural": "스토어 설정",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "store_order_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="스토어주문번호"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="상품명"),
                ),
                (
                    "option_name",
                    models.CharField(blank=True, max_length=200, verbose_name="옵션"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="수량")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="결제금액"
                    ),
                ),
                ("buyer_name", models.CharField(max_length=100, verbose_name="주문자")),
                (
                    "buyer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="연락처"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=100, verbose_name="수취인"),
                ),
                (
                    "receiver_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="수취인연락처"
                    ),
                ),
                (
                    "receiver_address",
                    models.TextField(blank=True, verbose_name="배송주소"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "신규주문"),
                            ("CONFIRMED", "확인"),
                            ("SHIPPED", "발송완료"),
                            ("DELIVERED", "배송완료"),
                            ("CANCELLED", "취소"),
                            ("RETURNED", "반품"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("ordered_at", models.DateTimeField(verbose_name="주문일시")),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="동기화일시"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "erp_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.order",
                        verbose_name="연결된 ERP 주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "스토어주문",
                "verbose_name_plural": "스토어주문",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "direction",
                    models.CharField(
                        choices=[("PULL", "수신"), ("PUSH", "발신")],
                        max_length=10,
                        verbose_name="방향",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="시작일시")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="전체건수"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="성공건수"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="오류건수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류내용"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "동기화이력",
                "verbose_name_plural": "동기화이력",
                "ordering": ["-started_at"],
            },
        ),
    ]
