# Generated by Django 5.2.12 on 2026-03-18 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('sales', '0007_alter_historicalorderitem_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['status'], name='idx_mktorder_status'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['ordered_at'], name='idx_mktorder_date'),
        ),
    ]
