# Generated by Django 5.2.12 on 2026-03-19 04:14

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_marketplaceorder_idx_mktorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmarketplaceconfig",
            name="client_id",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="Client ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmarketplaceconfig",
            name="client_secret",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="Client Secret"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceconfig",
            name="client_id",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="Client ID"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceconfig",
            name="client_secret",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="Client Secret"
            ),
        ),
    ]
