# Generated by Django 5.2.12 on 2026-03-24 02:02

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_historicalmarketplaceconfig_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmarketplaceorder",
            name="buyer_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmarketplaceorder",
            name="receiver_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmarketplaceorder",
            name="receiver_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="수취인연락처"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceorder",
            name="buyer_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceorder",
            name="receiver_address",
            field=apps.core.fields.EncryptedTextField(
                blank=True, verbose_name="배송주소"
            ),
        ),
        migrations.AlterField(
            model_name="marketplaceorder",
            name="receiver_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="수취인연락처"
            ),
        ),
    ]
