# Generated by Django 5.2.12 on 2026-03-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_historicalmarketplaceorder_buyer_phone_and_more'),
        ('sales', '0036_historicalpartner_commission_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='erp_quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.quotation', verbose_name='연결된 견적서'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='erp_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.quotation', verbose_name='연결된 견적서'),
        ),
    ]
