# Generated by Django 5.2.12 on 2026-04-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_erp_quotation_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='delivery_company',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='platform_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='플랫폼주문번호'),
        ),
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='platform_product_order_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='플랫폼상품주문번호'),
        ),
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='운송장번호'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_company',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='platform_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='플랫폼주문번호'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='platform_product_order_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='플랫폼상품주문번호'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='운송장번호'),
        ),
    ]
