# Generated by Django 5.2.12 on 2026-04-02 02:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_historicalproductmapping_productmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImportTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('store_type', models.CharField(choices=[('NAVER', '네이버 스마트스토어'), ('COUPANG', '쿠팡'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='스토어유형')),
                ('default_period', models.IntegerField(default=7, verbose_name='기본 조회기간(일)')),
                ('auto_confirm', models.BooleanField(default=True, verbose_name='자동 견적생성')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 가져오기 템플릿',
                'verbose_name_plural': 'historical 가져오기 템플릿',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('store_type', models.CharField(choices=[('NAVER', '네이버 스마트스토어'), ('COUPANG', '쿠팡'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='스토어유형')),
                ('default_period', models.IntegerField(default=7, verbose_name='기본 조회기간(일)')),
                ('auto_confirm', models.BooleanField(default=True, verbose_name='자동 견적생성')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '가져오기 템플릿',
                'verbose_name_plural': '가져오기 템플릿',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalproductmapping',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.importtemplate', verbose_name='템플릿'),
        ),
        migrations.AddField(
            model_name='productmapping',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='marketplace.importtemplate', verbose_name='템플릿'),
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together={('template', 'store_product_name', 'store_option_name')},
        ),
    ]
