# Generated by Django 5.2.12 on 2026-04-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_historicalimporttemplate_importtemplate_and_more'),
        ('sales', '0042_add_platform_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceorder',
            name='erp_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_orders', to='sales.order', verbose_name='연결된 ERP 주문'),
        ),
        migrations.AlterField(
            model_name='marketplaceorder',
            name='erp_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_quotations', to='sales.quotation', verbose_name='연결된 견적서'),
        ),
    ]
