# Generated by Django 5.2.12 on 2026-04-06 06:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_marketplaceorder_erp_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='import_error',
            field=models.TextField(blank=True, verbose_name='가져오기오류'),
        ),
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='import_status',
            field=models.CharField(choices=[('PENDING', '대기'), ('CUSTOMER_DONE', '고객등록완료'), ('QUOTATION_DONE', '견적생성완료'), ('ORDER_DONE', '주문전환완료'), ('SKIPPED', '건너뜀'), ('ERROR', '오류')], default='PENDING', max_length=20, verbose_name='가져오기상태'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='import_error',
            field=models.TextField(blank=True, verbose_name='가져오기오류'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='import_status',
            field=models.CharField(choices=[('PENDING', '대기'), ('CUSTOMER_DONE', '고객등록완료'), ('QUOTATION_DONE', '견적생성완료'), ('ORDER_DONE', '주문전환완료'), ('SKIPPED', '건너뜀'), ('ERROR', '오류')], default='PENDING', max_length=20, verbose_name='가져오기상태'),
        ),
        migrations.CreateModel(
            name='HistoricalImportSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stage', models.CharField(choices=[('FETCH', '데이터 수집'), ('PREVIEW', '미리보기'), ('CUSTOMER', '고객등록'), ('QUOTATION', '견적생성'), ('ORDER', '주문전환'), ('DONE', '완료')], default='FETCH', max_length=20, verbose_name='현재단계')),
                ('source_type', models.CharField(default='API', help_text='API 또는 EXCEL', max_length=10, verbose_name='소스유형')),
                ('platform', models.CharField(blank=True, max_length=20, verbose_name='플랫폼')),
                ('total_count', models.IntegerField(default=0, verbose_name='전체건수')),
                ('selected_count', models.IntegerField(default=0, verbose_name='선택건수')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 가져오기 세션',
                'verbose_name_plural': 'historical 가져오기 세션',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stage', models.CharField(choices=[('FETCH', '데이터 수집'), ('PREVIEW', '미리보기'), ('CUSTOMER', '고객등록'), ('QUOTATION', '견적생성'), ('ORDER', '주문전환'), ('DONE', '완료')], default='FETCH', max_length=20, verbose_name='현재단계')),
                ('source_type', models.CharField(default='API', help_text='API 또는 EXCEL', max_length=10, verbose_name='소스유형')),
                ('platform', models.CharField(blank=True, max_length=20, verbose_name='플랫폼')),
                ('total_count', models.IntegerField(default=0, verbose_name='전체건수')),
                ('selected_count', models.IntegerField(default=0, verbose_name='선택건수')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '가져오기 세션',
                'verbose_name_plural': '가져오기 세션',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalmarketplaceorder',
            name='import_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='marketplace.importsession', verbose_name='가져오기 세션'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.importsession', verbose_name='가져오기 세션'),
        ),
    ]
