# Generated by Django 5.2.12 on 2026-04-06 08:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_historicalmarketplaceorder_import_error_and_more'),
        ('sales', '0043_add_commission_base_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSettlementReconciliation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('store_module', models.CharField(max_length=50, verbose_name='스토어')),
                ('settlement_date', models.DateField(verbose_name='정산일')),
                ('expected_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='예상 정산액')),
                ('actual_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제 입금액')),
                ('difference', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='차이')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('MATCHED', '일치'), ('MISMATCHED', '불일치'), ('MANUAL', '수동처리')], default='PENDING', max_length=20, verbose_name='상태')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 정산 대사',
                'verbose_name_plural': 'historical 정산 대사',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SettlementReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('store_module', models.CharField(max_length=50, verbose_name='스토어')),
                ('settlement_date', models.DateField(verbose_name='정산일')),
                ('expected_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='예상 정산액')),
                ('actual_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='실제 입금액')),
                ('difference', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='차이')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('MATCHED', '일치'), ('MISMATCHED', '불일치'), ('MANUAL', '수동처리')], default='PENDING', max_length=20, verbose_name='상태')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_reconciliations', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '정산 대사',
                'verbose_name_plural': '정산 대사',
                'ordering': ['-settlement_date', '-pk'],
                'indexes': [models.Index(fields=['status'], name='idx_recon_status'), models.Index(fields=['settlement_date'], name='idx_recon_date')],
            },
        ),
    ]
