# Generated by Django 5.2.12 on 2026-04-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_historicalsettlementreconciliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsynclog',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막재시도'),
        ),
        migrations.AddField(
            model_name='historicalsynclog',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='재시도횟수'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막재시도'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='재시도횟수'),
        ),
    ]
