# Generated by Django 5.2.12 on 2026-04-12 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitornda',
            name='visit_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nda', to='visitor.visitlog', verbose_name='방문기록'),
        ),
    ]
