# Generated by Django 5.2.12 on 2026-03-17 01:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ADDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="도메인명"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="예: corp.example.com",
                        max_length=255,
                        unique=True,
                        verbose_name="도메인 주소",
                    ),
                ),
                (
                    "ldap_server",
                    models.CharField(
                        help_text="예: ldap://dc01.corp.example.com:389",
                        max_length=255,
                        verbose_name="LDAP 서버",
                    ),
                ),
                (
                    "ldap_bind_dn",
                    models.CharField(
                        help_text="예: CN=svc_erp,OU=ServiceAccounts,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="바인드 DN",
                    ),
                ),
                (
                    "ldap_bind_password",
                    models.CharField(max_length=255, verbose_name="바인드 비밀번호"),
                ),
                (
                    "base_dn",
                    models.CharField(
                        help_text="예: DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="Base DN",
                    ),
                ),
                (
                    "user_search_base",
                    models.CharField(
                        blank=True,
                        help_text="예: OU=Users,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="사용자 검색 Base",
                    ),
                ),
                (
                    "group_search_base",
                    models.CharField(
                        blank=True,
                        help_text="예: OU=Groups,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="그룹 검색 Base",
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, verbose_name="SSL 사용"),
                ),
                (
                    "use_start_tls",
                    models.BooleanField(default=True, verbose_name="StartTLS 사용"),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="자동 동기화"),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="동기화 주기(분)"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 도메인",
                "verbose_name_plural": "AD 도메인",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ADGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(max_length=500, unique=True, verbose_name="DN"),
                ),
                (
                    "sam_account_name",
                    models.CharField(max_length=256, verbose_name="sAMAccountName"),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=256, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "보안 그룹"),
                            ("DISTRIBUTION", "배포 그룹"),
                        ],
                        default="SECURITY",
                        max_length=20,
                        verbose_name="그룹 유형",
                    ),
                ),
                (
                    "group_scope",
                    models.CharField(
                        choices=[
                            ("DOMAIN_LOCAL", "도메인 로컬"),
                            ("GLOBAL", "글로벌"),
                            ("UNIVERSAL", "유니버설"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                        verbose_name="그룹 범위",
                    ),
                ),
                (
                    "mapped_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "관리자"),
                            ("manager", "매니저"),
                            ("staff", "직원"),
                        ],
                        help_text="이 AD 그룹의 구성원에게 자동 부여할 ERP 역할",
                        max_length=20,
                        verbose_name="매핑된 ERP 역할",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 그룹",
                "verbose_name_plural": "AD 그룹",
                "ordering": ["sam_account_name"],
            },
        ),
        migrations.CreateModel(
            name="ADGroupPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="정책명")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN_ROLE", "역할 부여"),
                            ("ASSIGN_DEPARTMENT", "부서 배정"),
                            ("GRANT_MODULE_ACCESS", "모듈 접근 허용"),
                        ],
                        max_length=30,
                        verbose_name="적용 동작",
                    ),
                ),
                (
                    "action_value",
                    models.CharField(
                        help_text="역할명(admin/manager/staff), 부서ID, 모듈명 등",
                        max_length=100,
                        verbose_name="동작 값",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="낮을수록 높은 우선순위",
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="ad.adgroup",
                        verbose_name="AD 그룹",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 그룹 정책",
                "verbose_name_plural": "AD 그룹 정책",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ADOrganizationalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(max_length=500, unique=True, verbose_name="DN"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="OU명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ous",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "mapped_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="이 OU에 매핑할 ERP 부서",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_ous",
                        to="hr.department",
                        verbose_name="매핑된 부서",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ad.adorganizationalunit",
                        verbose_name="상위 OU",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 조직단위(OU)",
                "verbose_name_plural": "AD 조직단위(OU)",
                "ordering": ["distinguished_name"],
            },
        ),
        migrations.AddField(
            model_name="adgroup",
            name="ou",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="ad.adorganizationalunit",
                verbose_name="소속 OU",
            ),
        ),
        migrations.CreateModel(
            name="ADSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "전체 동기화"),
                            ("INCREMENTAL", "증분 동기화"),
                            ("MANUAL", "수동 동기화"),
                        ],
                        max_length=20,
                        verbose_name="동기화 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "진행중"),
                            ("SUCCESS", "성공"),
                            ("PARTIAL", "부분성공"),
                            ("FAILED", "실패"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작시각"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료시각"
                    ),
                ),
                (
                    "users_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="생성된 사용자"
                    ),
                ),
                (
                    "users_updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="수정된 사용자"
                    ),
                ),
                (
                    "users_disabled",
                    models.PositiveIntegerField(
                        default=0, verbose_name="비활성화 사용자"
                    ),
                ),
                (
                    "groups_synced",
                    models.PositiveIntegerField(
                        default=0, verbose_name="동기화된 그룹"
                    ),
                ),
                (
                    "ous_synced",
                    models.PositiveIntegerField(default=0, verbose_name="동기화된 OU"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="오류 수"),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, verbose_name="오류 상세"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="실행자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 동기화 로그",
                "verbose_name_plural": "AD 동기화 로그",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ADUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(max_length=500, unique=True, verbose_name="DN"),
                ),
                (
                    "sam_account_name",
                    models.CharField(max_length=256, verbose_name="sAMAccountName"),
                ),
                (
                    "user_principal_name",
                    models.CharField(
                        blank=True,
                        help_text="예: user@corp.example.com",
                        max_length=256,
                        verbose_name="UPN",
                    ),
                ),
                (
                    "object_guid",
                    models.CharField(
                        help_text="AD 고유 식별자",
                        max_length=36,
                        unique=True,
                        verbose_name="objectGUID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "동기화됨"),
                            ("PENDING", "대기중"),
                            ("ERROR", "오류"),
                            ("DISABLED", "비활성"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="동기화 상태",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "ad_enabled",
                    models.BooleanField(default=True, verbose_name="AD 계정 활성"),
                ),
                (
                    "ad_locked",
                    models.BooleanField(default=False, verbose_name="AD 계정 잠금"),
                ),
                (
                    "ad_password_last_set",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="비밀번호 마지막 변경"
                    ),
                ),
                (
                    "ad_last_logon",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AD 마지막 로그온"
                    ),
                ),
                (
                    "sync_error_message",
                    models.TextField(blank=True, verbose_name="동기화 오류 메시지"),
                ),
                (
                    "ad_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_mappings",
                        to="ad.adgroup",
                        verbose_name="AD 그룹",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "ou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_mappings",
                        to="ad.adorganizationalunit",
                        verbose_name="소속 OU",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_mapping",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ERP 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD 사용자 매핑",
                "verbose_name_plural": "AD 사용자 매핑",
                "ordering": ["sam_account_name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalADDomain",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="도메인명"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="예: corp.example.com",
                        max_length=255,
                        verbose_name="도메인 주소",
                    ),
                ),
                (
                    "ldap_server",
                    models.CharField(
                        help_text="예: ldap://dc01.corp.example.com:389",
                        max_length=255,
                        verbose_name="LDAP 서버",
                    ),
                ),
                (
                    "ldap_bind_dn",
                    models.CharField(
                        help_text="예: CN=svc_erp,OU=ServiceAccounts,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="바인드 DN",
                    ),
                ),
                (
                    "ldap_bind_password",
                    models.CharField(max_length=255, verbose_name="바인드 비밀번호"),
                ),
                (
                    "base_dn",
                    models.CharField(
                        help_text="예: DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="Base DN",
                    ),
                ),
                (
                    "user_search_base",
                    models.CharField(
                        blank=True,
                        help_text="예: OU=Users,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="사용자 검색 Base",
                    ),
                ),
                (
                    "group_search_base",
                    models.CharField(
                        blank=True,
                        help_text="예: OU=Groups,DC=corp,DC=example,DC=com",
                        max_length=255,
                        verbose_name="그룹 검색 Base",
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, verbose_name="SSL 사용"),
                ),
                (
                    "use_start_tls",
                    models.BooleanField(default=True, verbose_name="StartTLS 사용"),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="자동 동기화"),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="동기화 주기(분)"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 도메인",
                "verbose_name_plural": "historical AD 도메인",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalADGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(db_index=True, max_length=500, verbose_name="DN"),
                ),
                (
                    "sam_account_name",
                    models.CharField(max_length=256, verbose_name="sAMAccountName"),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=256, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "보안 그룹"),
                            ("DISTRIBUTION", "배포 그룹"),
                        ],
                        default="SECURITY",
                        max_length=20,
                        verbose_name="그룹 유형",
                    ),
                ),
                (
                    "group_scope",
                    models.CharField(
                        choices=[
                            ("DOMAIN_LOCAL", "도메인 로컬"),
                            ("GLOBAL", "글로벌"),
                            ("UNIVERSAL", "유니버설"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                        verbose_name="그룹 범위",
                    ),
                ),
                (
                    "mapped_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "관리자"),
                            ("manager", "매니저"),
                            ("staff", "직원"),
                        ],
                        help_text="이 AD 그룹의 구성원에게 자동 부여할 ERP 역할",
                        max_length=20,
                        verbose_name="매핑된 ERP 역할",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ou",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.adorganizationalunit",
                        verbose_name="소속 OU",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 그룹",
                "verbose_name_plural": "historical AD 그룹",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalADGroupPolicy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="정책명")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ASSIGN_ROLE", "역할 부여"),
                            ("ASSIGN_DEPARTMENT", "부서 배정"),
                            ("GRANT_MODULE_ACCESS", "모듈 접근 허용"),
                        ],
                        max_length=30,
                        verbose_name="적용 동작",
                    ),
                ),
                (
                    "action_value",
                    models.CharField(
                        help_text="역할명(admin/manager/staff), 부서ID, 모듈명 등",
                        max_length=100,
                        verbose_name="동작 값",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="낮을수록 높은 우선순위",
                        verbose_name="우선순위",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.adgroup",
                        verbose_name="AD 그룹",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 그룹 정책",
                "verbose_name_plural": "historical AD 그룹 정책",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalADOrganizationalUnit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(db_index=True, max_length=500, verbose_name="DN"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="OU명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapped_department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="이 OU에 매핑할 ERP 부서",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.department",
                        verbose_name="매핑된 부서",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.adorganizationalunit",
                        verbose_name="상위 OU",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 조직단위(OU)",
                "verbose_name_plural": "historical AD 조직단위(OU)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalADSyncLog",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "전체 동기화"),
                            ("INCREMENTAL", "증분 동기화"),
                            ("MANUAL", "수동 동기화"),
                        ],
                        max_length=20,
                        verbose_name="동기화 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "진행중"),
                            ("SUCCESS", "성공"),
                            ("PARTIAL", "부분성공"),
                            ("FAILED", "실패"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="시작시각"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료시각"
                    ),
                ),
                (
                    "users_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="생성된 사용자"
                    ),
                ),
                (
                    "users_updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="수정된 사용자"
                    ),
                ),
                (
                    "users_disabled",
                    models.PositiveIntegerField(
                        default=0, verbose_name="비활성화 사용자"
                    ),
                ),
                (
                    "groups_synced",
                    models.PositiveIntegerField(
                        default=0, verbose_name="동기화된 그룹"
                    ),
                ),
                (
                    "ous_synced",
                    models.PositiveIntegerField(default=0, verbose_name="동기화된 OU"),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(default=0, verbose_name="오류 수"),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, verbose_name="오류 상세"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="실행자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 동기화 로그",
                "verbose_name_plural": "historical AD 동기화 로그",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalADUserMapping",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "distinguished_name",
                    models.CharField(db_index=True, max_length=500, verbose_name="DN"),
                ),
                (
                    "sam_account_name",
                    models.CharField(max_length=256, verbose_name="sAMAccountName"),
                ),
                (
                    "user_principal_name",
                    models.CharField(
                        blank=True,
                        help_text="예: user@corp.example.com",
                        max_length=256,
                        verbose_name="UPN",
                    ),
                ),
                (
                    "object_guid",
                    models.CharField(
                        db_index=True,
                        help_text="AD 고유 식별자",
                        max_length=36,
                        verbose_name="objectGUID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "동기화됨"),
                            ("PENDING", "대기중"),
                            ("ERROR", "오류"),
                            ("DISABLED", "비활성"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="동기화 상태",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 동기화"
                    ),
                ),
                (
                    "ad_enabled",
                    models.BooleanField(default=True, verbose_name="AD 계정 활성"),
                ),
                (
                    "ad_locked",
                    models.BooleanField(default=False, verbose_name="AD 계정 잠금"),
                ),
                (
                    "ad_password_last_set",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="비밀번호 마지막 변경"
                    ),
                ),
                (
                    "ad_last_logon",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AD 마지막 로그온"
                    ),
                ),
                (
                    "sync_error_message",
                    models.TextField(blank=True, verbose_name="동기화 오류 메시지"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.addomain",
                        verbose_name="도메인",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ou",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ad.adorganizationalunit",
                        verbose_name="소속 OU",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ERP 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AD 사용자 매핑",
                "verbose_name_plural": "historical AD 사용자 매핑",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="adgroup",
            index=models.Index(fields=["sam_account_name"], name="idx_adgroup_sam"),
        ),
        migrations.AddIndex(
            model_name="adsynclog",
            index=models.Index(fields=["status"], name="idx_adsynclog_status"),
        ),
        migrations.AddIndex(
            model_name="adsynclog",
            index=models.Index(fields=["-started_at"], name="idx_adsynclog_started"),
        ),
        migrations.AddIndex(
            model_name="adusermapping",
            index=models.Index(fields=["sam_account_name"], name="idx_admapping_sam"),
        ),
        migrations.AddIndex(
            model_name="adusermapping",
            index=models.Index(fields=["object_guid"], name="idx_admapping_guid"),
        ),
        migrations.AddIndex(
            model_name="adusermapping",
            index=models.Index(fields=["sync_status"], name="idx_admapping_sync"),
        ),
    ]
