# Generated by Django 5.2.12 on 2026-03-19 04:14

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addomain",
            name="ldap_bind_password",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="바인드 비밀번호"
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdomain",
            name="ldap_bind_password",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="바인드 비밀번호"
            ),
        ),
    ]
