# Generated by Django 5.2.12 on 2026-03-16 12:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 읽은 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대화 참여자',
                'verbose_name_plural': '대화 참여자',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='대화방 이름')),
                ('room_type', models.CharField(choices=[('direct', '1:1 대화'), ('group', '그룹 대화')], default='direct', max_length=10, verbose_name='유형')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='messenger.ChatParticipant', to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
            ],
            options={
                'verbose_name': '대화방',
                'verbose_name_plural': '대화방',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.chatroom', verbose_name='대화방'),
        ),
        migrations.CreateModel(
            name='HistoricalChatRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='대화방 이름')),
                ('room_type', models.CharField(choices=[('direct', '1:1 대화'), ('group', '그룹 대화')], default='direct', max_length=10, verbose_name='유형')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 대화방',
                'verbose_name_plural': 'historical 대화방',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('message_type', models.CharField(choices=[('text', '텍스트'), ('file', '파일'), ('image', '이미지')], default='text', max_length=10, verbose_name='메시지 유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='messenger/', verbose_name='첨부파일')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 시간')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chatroom', verbose_name='대화방')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('room', 'user')},
        ),
    ]
