# Generated by Django 5.2.12 on 2026-03-19 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_historicalchatparticipant_historicalmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='historicalchatparticipant',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalchatparticipant',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='historicalchatparticipant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
        migrations.AddField(
            model_name='historicalchatparticipant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='historicalchatparticipant',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='수정일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='수정일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
        migrations.AddField(
            model_name='message',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', through='messenger.ChatParticipant', through_fields=('room', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'sent_at'], name='idx_message_room_sent'),
        ),
    ]
