# Generated by Django 5.2.12 on 2026-03-23 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chatparticipant_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatparticipant',
            options={'ordering': ['-joined_at'], 'verbose_name': '대화 참여자', 'verbose_name_plural': '대화 참여자'},
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uq_chatparticipant_room_user'),
        ),
    ]
