# Generated by Django 5.2.12 on 2026-03-24 01:33

import apps.core.attachment
import apps.messenger.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_alter_chatparticipant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmessage",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "xlsx",
                            "xls",
                            "csv",
                            "doc",
                            "docx",
                            "hwp",
                            "hwpx",
                            "zip",
                            "txt",
                        ]
                    ),
                    apps.core.attachment.validate_file_content_type,
                    apps.messenger.models.validate_file_size,
                ],
                verbose_name="첨부파일",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messenger/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "xlsx",
                            "xls",
                            "csv",
                            "doc",
                            "docx",
                            "hwp",
                            "hwpx",
                            "zip",
                            "txt",
                        ]
                    ),
                    apps.core.attachment.validate_file_content_type,
                    apps.messenger.models.validate_file_size,
                ],
                verbose_name="첨부파일",
            ),
        ),
    ]
