# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.attachment
import apps.core.storage
import apps.messenger.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_historicalmessage_file_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='원본파일명'),
        ),
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='원본파일명'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.storage.hashed_upload_path('messenger'), validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'xlsx', 'xls', 'csv', 'doc', 'docx', 'hwp', 'hwpx', 'zip', 'txt']), apps.core.attachment.validate_file_content_type, apps.messenger.models.validate_file_size], verbose_name='첨부파일'),
        ),
    ]
