# Generated by Django 6.0.3 on 2026-03-16 05:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalServiceRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "request_number",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="AS번호"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="시리얼번호"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("WARRANTY", "보증수리"),
                            ("PAID", "유상수리"),
                            ("EXCHANGE", "교환"),
                            ("REFUND", "환불"),
                        ],
                        default="WARRANTY",
                        max_length=10,
                        verbose_name="요청유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "접수"),
                            ("INSPECTING", "검수중"),
                            ("REPAIRING", "수리중"),
                            ("COMPLETED", "완료"),
                            ("RETURNED", "반송완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("symptom", models.TextField(verbose_name="증상/내용")),
                ("received_date", models.DateField(verbose_name="접수일")),
                (
                    "completed_date",
                    models.DateField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "is_warranty",
                    models.BooleanField(default=False, verbose_name="보증기간내"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sales.customer",
                        verbose_name="고객",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical AS 요청",
                "verbose_name_plural": "historical AS 요청",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "request_number",
                    models.CharField(max_length=30, unique=True, verbose_name="AS번호"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="시리얼번호"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("WARRANTY", "보증수리"),
                            ("PAID", "유상수리"),
                            ("EXCHANGE", "교환"),
                            ("REFUND", "환불"),
                        ],
                        default="WARRANTY",
                        max_length=10,
                        verbose_name="요청유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "접수"),
                            ("INSPECTING", "검수중"),
                            ("REPAIRING", "수리중"),
                            ("COMPLETED", "완료"),
                            ("RETURNED", "반송완료"),
                            ("CANCELLED", "취소"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("symptom", models.TextField(verbose_name="증상/내용")),
                ("received_date", models.DateField(verbose_name="접수일")),
                (
                    "completed_date",
                    models.DateField(blank=True, null=True, verbose_name="완료일"),
                ),
                (
                    "is_warranty",
                    models.BooleanField(default=False, verbose_name="보증기간내"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="sales.customer",
                        verbose_name="고객",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "AS 요청",
                "verbose_name_plural": "AS 요청",
                "ordering": ["-received_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="RepairRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("repair_date", models.DateField(verbose_name="수리일")),
                ("description", models.TextField(verbose_name="수리내용")),
                ("parts_used", models.TextField(blank=True, verbose_name="사용부품")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="수리비용",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수리담당",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repairs",
                        to="service.servicerequest",
                        verbose_name="AS 요청",
                    ),
                ),
            ],
            options={
                "verbose_name": "수리이력",
                "verbose_name_plural": "수리이력",
                "ordering": ["-repair_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalRepairRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("repair_date", models.DateField(verbose_name="수리일")),
                ("description", models.TextField(verbose_name="수리내용")),
                ("parts_used", models.TextField(blank=True, verbose_name="사용부품")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="수리비용",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수리담당",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service.servicerequest",
                        verbose_name="AS 요청",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 수리이력",
                "verbose_name_plural": "historical 수리이력",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
