# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_idx_product_type_and_more'),
        ('sales', '0004_order_idx_order_status_order_idx_order_date_and_more'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='idx_service_status'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['received_date'], name='idx_service_date'),
        ),
    ]
