# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicerequest_idx_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicerequest',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='AS번호'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='AS번호'),
        ),
    ]
