# Generated by Django 5.2.12 on 2026-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_number_convert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-request_number'], 'verbose_name': 'AS 요청', 'verbose_name_plural': 'AS 요청'},
        ),
    ]
