# Generated by Django 5.2.12 on 2026-04-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_historicalpartner_approval_status_and_more'),
        ('service', '0005_alter_servicerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicerequest',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.order', verbose_name='관련주문'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='sales.order', verbose_name='관련주문'),
        ),
    ]
