# Generated by Django 5.2.12 on 2026-04-15 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        ('service', '0006_historicalservicerequest_order_servicerequest_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'received_date'], name='idx_service_status_date'),
        ),
    ]
