# Generated by Django 5.2.12 on 2026-04-06 04:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_alter_approvalrequest_category_and_more'),
        ('asset', '0001_initial'),
        ('hr', '0011_employeeprofile_contract_end_and_more'),
        ('purchase', '0014_add_is_taxable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='condition_assessment',
            field=models.TextField(blank=True, verbose_name='상태평가'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_assets', to='approval.approvalrequest', verbose_name='처분결재'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='source_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='purchase.goodsreceiptitem', verbose_name='입고출처'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='condition_assessment',
            field=models.TextField(blank=True, verbose_name='상태평가'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='disposal_approval',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='approval.approvalrequest', verbose_name='처분결재'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='source_receipt_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.goodsreceiptitem', verbose_name='입고출처'),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('transfer_date', models.DateField(verbose_name='이관일')),
                ('from_location', models.CharField(blank=True, max_length=200, verbose_name='이전위치')),
                ('to_location', models.CharField(blank=True, max_length=200, verbose_name='이관위치')),
                ('reason', models.TextField(blank=True, verbose_name='이관사유')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='asset.fixedasset', verbose_name='자산')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to='hr.department', verbose_name='이전부서')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='이전관리자')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_in', to='hr.department', verbose_name='이관부서')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='이관관리자')),
            ],
            options={
                'verbose_name': '자산이관',
                'verbose_name_plural': '자산이관',
                'ordering': ['-transfer_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssetTransfer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('transfer_date', models.DateField(verbose_name='이관일')),
                ('from_location', models.CharField(blank=True, max_length=200, verbose_name='이전위치')),
                ('to_location', models.CharField(blank=True, max_length=200, verbose_name='이관위치')),
                ('reason', models.TextField(blank=True, verbose_name='이관사유')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.fixedasset', verbose_name='자산')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('from_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.department', verbose_name='이전부서')),
                ('from_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='이전관리자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.department', verbose_name='이관부서')),
                ('to_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='이관관리자')),
            ],
            options={
                'verbose_name': 'historical 자산이관',
                'verbose_name_plural': 'historical 자산이관',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
