# Generated by Django 5.2.12 on 2026-04-07 00:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_fixedasset_asset_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='위치명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='위치코드')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='건물')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='층')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='호실/구역')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='asset.location', verbose_name='상위위치')),
            ],
            options={
                'verbose_name': '자산위치',
                'verbose_name_plural': '자산위치',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='위치명')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='위치코드')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='건물')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='층')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='호실/구역')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.location', verbose_name='상위위치')),
            ],
            options={
                'verbose_name': 'historical 자산위치',
                'verbose_name_plural': 'historical 자산위치',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_managed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='asset.location', verbose_name='이전관리위치'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_managed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='asset.location', verbose_name='이관관리위치'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='managed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='asset.location', verbose_name='관리위치'),
        ),
        migrations.AddField(
            model_name='historicalassettransfer',
            name='from_managed_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.location', verbose_name='이전관리위치'),
        ),
        migrations.AddField(
            model_name='historicalassettransfer',
            name='to_managed_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.location', verbose_name='이관관리위치'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='managed_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.location', verbose_name='관리위치'),
        ),
    ]
