# Generated by Django 5.2.12 on 2026-04-13 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_assetmaintenance_historicalassetmaintenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetaudititem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reservationrule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assetaudititem',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='asset.assetaudit', verbose_name='실사'),
        ),
        migrations.AlterField(
            model_name='assetreservation',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_reservations', to=settings.AUTH_USER_MODEL, verbose_name='예약자'),
        ),
        migrations.AlterField(
            model_name='reservationrule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='asset.reservableasset', verbose_name='예약자산'),
        ),
        migrations.AddConstraint(
            model_name='assetaudititem',
            constraint=models.UniqueConstraint(fields=('audit', 'asset'), name='uq_asset_audit_item'),
        ),
        migrations.AddConstraint(
            model_name='reservationrule',
            constraint=models.UniqueConstraint(fields=('asset', 'day_of_week'), name='uq_reservation_rule_asset_day'),
        ),
    ]
