# Generated by Django 5.2.12 on 2026-04-15 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_approvaldelegation_approvallinetemplate_and_more'),
        ('asset', '0006_alter_assetaudititem_unique_together_and_more'),
        ('hr', '0013_employeeprofile_idx_emp_dept_date_and_more'),
        ('purchase', '0017_goodsreceipt_idx_gr_receipt_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['asset', 'transfer_date'], name='idx_transfer_asset_dt'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['asset', 'year', 'month'], name='idx_deprec_asset_yr_mo'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status', 'acquisition_date'], name='idx_asset_status_acq'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['category', 'status'], name='idx_asset_cat_status'),
        ),
    ]
