# Generated by Django 6.0.3 on 2026-03-16 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.TextField(verbose_name="내용")),
                (
                    "noti_type",
                    models.CharField(
                        choices=[
                            ("STOCK_LOW", "재고부족"),
                            ("ORDER_NEW", "신규주문"),
                            ("SERVICE_DUE", "AS기한초과"),
                            ("PRODUCTION", "생산완료"),
                            ("SYSTEM", "시스템"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="읽음")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="링크"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "ordering": ["-created_at"],
            },
        ),
    ]
