# Generated by Django 6.0.3 on 2026-03-16 07:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "xlsx",
                                    "xls",
                                    "csv",
                                    "doc",
                                    "docx",
                                    "hwp",
                                    "hwpx",
                                    "zip",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="파일",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="원본파일명"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="파일크기(bytes)"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("EVIDENCE", "증빙"),
                            ("RECEIPT", "영수증"),
                            ("INVOICE", "세금계산서"),
                            ("CONTRACT", "계약서"),
                            ("PHOTO", "사진"),
                            ("REPORT", "보고서"),
                            ("OTHER", "기타"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="문서유형",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
