# Generated by Django 5.2.12 on 2026-03-19 04:41

import apps.core.attachment
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="attachments/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "xlsx",
                            "xls",
                            "csv",
                            "doc",
                            "docx",
                            "hwp",
                            "hwpx",
                            "zip",
                            "txt",
                        ]
                    ),
                    apps.core.attachment.validate_file_content_type,
                ],
                verbose_name="파일",
            ),
        ),
    ]
