# Generated by Django 5.2.12 on 2026-03-20 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DASHBOARD', '감사 대시보드'), ('ACCESS_LOG', '시스템 접근 로그'), ('DATA_CHANGE', '데이터 변경 이력'), ('LOGIN_HISTORY', '로그인/보안 이벤트'), ('AUDIT_LOG', '감사 열람 기록')], max_length=30, verbose_name='열람 섹션')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('query_params', models.TextField(blank=True, verbose_name='조회 조건')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='열람일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='열람자')),
            ],
            options={
                'verbose_name': '감사 열람 기록',
                'verbose_name_plural': '감사 열람 기록',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'accessed_at'], name='idx_auditlog_user_date'), models.Index(fields=['section'], name='idx_auditlog_section')],
            },
        ),
    ]
