# Generated by Django 5.2.12 on 2026-03-24 04:36

import apps.core.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auditaccesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSystemConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NTS", "국세청 API"),
                            ("MARKETPLACE", "마켓플레이스"),
                            ("EMAIL", "이메일"),
                            ("GENERAL", "일반"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="설정키")),
                (
                    "value",
                    apps.core.fields.EncryptedCharField(
                        blank=True, max_length=1000, verbose_name="설정값"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="마스킹 표시 여부",
                        verbose_name="민감정보",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("password", "비밀번호"),
                            ("url", "URL"),
                            ("number", "숫자"),
                            ("boolean", "참/거짓"),
                            ("file", "파일경로"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="값 타입",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 시스템 설정",
                "verbose_name_plural": "historical 시스템 설정",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NTS", "국세청 API"),
                            ("MARKETPLACE", "마켓플레이스"),
                            ("EMAIL", "이메일"),
                            ("GENERAL", "일반"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="설정키")),
                (
                    "value",
                    apps.core.fields.EncryptedCharField(
                        blank=True, max_length=1000, verbose_name="설정값"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="표시명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="마스킹 표시 여부",
                        verbose_name="민감정보",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("password", "비밀번호"),
                            ("url", "URL"),
                            ("number", "숫자"),
                            ("boolean", "참/거짓"),
                            ("file", "파일경로"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="값 타입",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시스템 설정",
                "verbose_name_plural": "시스템 설정",
                "ordering": ["category", "key"],
                "unique_together": {("category", "key")},
            },
        ),
    ]
