# Generated by Django 5.2.12 on 2026-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_system_config_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemconfig',
            name='category',
            field=models.CharField(choices=[('NTS', '국세청 API'), ('MARKETPLACE', '마켓플레이스'), ('SHIPPING', '택배/배송'), ('EMAIL', '이메일'), ('AI', 'AI/자동화'), ('ADDRESS', '주소검색'), ('GENERAL', '일반'), ('COMPANY', '회사정보'), ('HR', '인사'), ('SECURITY', '보안'), ('BACKUP', '백업/복구')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='category',
            field=models.CharField(choices=[('NTS', '국세청 API'), ('MARKETPLACE', '마켓플레이스'), ('SHIPPING', '택배/배송'), ('EMAIL', '이메일'), ('AI', 'AI/자동화'), ('ADDRESS', '주소검색'), ('GENERAL', '일반'), ('COMPANY', '회사정보'), ('HR', '인사'), ('SECURITY', '보안'), ('BACKUP', '백업/복구')], max_length=20, verbose_name='카테고리'),
        ),
    ]
