# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.attachment
import apps.core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicalsystemconfig_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=apps.core.storage.hashed_upload_path('attachments'), validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'xlsx', 'xls', 'csv', 'doc', 'docx', 'hwp', 'hwpx', 'zip', 'txt']), apps.core.attachment.validate_file_content_type], verbose_name='파일'),
        ),
    ]
