# Generated by Django 5.2.12 on 2026-04-14 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalnotificationchannel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=200, verbose_name='뷰 이름')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='행 수')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='다운로드 시각')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_downloads', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Excel 다운로드 로그',
                'verbose_name_plural': 'Excel 다운로드 로그',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['user', '-downloaded_at'], name='idx_excel_dl_user_date')],
            },
        ),
    ]
