# Generated by Django 6.0.3 on 2026-03-16 05:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0002_historicalorder_grand_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "임대료/시설비"),
                            ("LABOR", "인건비"),
                            ("EQUIPMENT", "장비/감가상각"),
                            ("INSURANCE", "보험료"),
                            ("TELECOM", "통신비"),
                            ("SUBSCRIPTION", "구독/라이선스"),
                            ("OTHER", "기타 고정비"),
                        ],
                        max_length=20,
                        verbose_name="비용구분",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="비용명")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                ("month", models.DateField(verbose_name="해당월")),
                (
                    "is_recurring",
                    models.BooleanField(default=True, verbose_name="반복비용"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "고정비",
                "verbose_name_plural": "고정비",
                "ordering": ["-month", "category"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFixedCost",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "임대료/시설비"),
                            ("LABOR", "인건비"),
                            ("EQUIPMENT", "장비/감가상각"),
                            ("INSURANCE", "보험료"),
                            ("TELECOM", "통신비"),
                            ("SUBSCRIPTION", "구독/라이선스"),
                            ("OTHER", "기타 고정비"),
                        ],
                        max_length=20,
                        verbose_name="비용구분",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="비용명")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                ("month", models.DateField(verbose_name="해당월")),
                (
                    "is_recurring",
                    models.BooleanField(default=True, verbose_name="반복비용"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 고정비",
                "verbose_name_plural": "historical 고정비",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTaxInvoice",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="세금계산서번호"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("SALES", "매출"), ("PURCHASE", "매입")],
                        max_length=10,
                        verbose_name="유형",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="발행일")),
                (
                    "supply_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="공급가액"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="부가세"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="합계"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="적요")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sales.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sales.partner",
                        verbose_name="거래처",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 세금계산서",
                "verbose_name_plural": "historical 세금계산서",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTaxRate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=50, verbose_name="세율명")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="세율코드"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="세율(%)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본세율"),
                ),
                ("effective_from", models.DateField(verbose_name="시행일")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 세율",
                "verbose_name_plural": "historical 세율",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWithholdingTax",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "소득세"),
                            ("CORPORATE", "법인세"),
                            ("RESIDENT", "주민세"),
                        ],
                        max_length=20,
                        verbose_name="세목",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(max_length=100, verbose_name="소득자명"),
                ),
                ("payment_date", models.DateField(verbose_name="지급일")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="지급액"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="세율(%)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="원천징수액"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="실지급액"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 원천징수",
                "verbose_name_plural": "historical 원천징수",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="세금계산서번호"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("SALES", "매출"), ("PURCHASE", "매입")],
                        max_length=10,
                        verbose_name="유형",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="발행일")),
                (
                    "supply_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="공급가액"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="부가세"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="합계"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="적요")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_invoices",
                        to="sales.partner",
                        verbose_name="거래처",
                    ),
                ),
            ],
            options={
                "verbose_name": "세금계산서",
                "verbose_name_plural": "세금계산서",
                "ordering": ["-issue_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=50, verbose_name="세율명")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="세율코드"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="세율(%)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본세율"),
                ),
                ("effective_from", models.DateField(verbose_name="시행일")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "세율",
                "verbose_name_plural": "세율",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WithholdingTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "소득세"),
                            ("CORPORATE", "법인세"),
                            ("RESIDENT", "주민세"),
                        ],
                        max_length=20,
                        verbose_name="세목",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(max_length=100, verbose_name="소득자명"),
                ),
                ("payment_date", models.DateField(verbose_name="지급일")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="지급액"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="세율(%)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="원천징수액"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="실지급액"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "원천징수",
                "verbose_name_plural": "원천징수",
                "ordering": ["-payment_date"],
            },
        ),
    ]
