# Generated by Django 6.0.3 on 2026-03-16 06:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="계정코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="계정명")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "자산"),
                            ("LIABILITY", "부채"),
                            ("EQUITY", "자본"),
                            ("REVENUE", "수익"),
                            ("EXPENSE", "비용"),
                        ],
                        max_length=20,
                        verbose_name="계정유형",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.accountcode",
                        verbose_name="상위계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "계정과목",
                "verbose_name_plural": "계정과목",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAccountCode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="계정코드"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="계정명")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "자산"),
                            ("LIABILITY", "부채"),
                            ("EQUITY", "자본"),
                            ("REVENUE", "수익"),
                            ("EXPENSE", "비용"),
                        ],
                        max_length=20,
                        verbose_name="계정유형",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounting.accountcode",
                        verbose_name="상위계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 계정과목",
                "verbose_name_plural": "historical 계정과목",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVoucher",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "voucher_number",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="전표번호"
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "입금"),
                            ("PAYMENT", "출금"),
                            ("TRANSFER", "대체"),
                        ],
                        max_length=10,
                        verbose_name="전표유형",
                    ),
                ),
                ("voucher_date", models.DateField(verbose_name="전표일")),
                ("description", models.CharField(max_length=200, verbose_name="적요")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUBMITTED", "제출"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="승인상태",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 전표",
                "verbose_name_plural": "historical 전표",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "voucher_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="전표번호"
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "입금"),
                            ("PAYMENT", "출금"),
                            ("TRANSFER", "대체"),
                        ],
                        max_length=10,
                        verbose_name="전표유형",
                    ),
                ),
                ("voucher_date", models.DateField(verbose_name="전표일")),
                ("description", models.CharField(max_length=200, verbose_name="적요")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUBMITTED", "제출"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="승인상태",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vouchers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "전표",
                "verbose_name_plural": "전표",
                "ordering": ["-voucher_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="VoucherLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="차변"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="대변"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="적요"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.accountcode",
                        verbose_name="계정과목",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "전표항목",
                "verbose_name_plural": "전표항목",
            },
        ),
    ]
