# Generated by Django 6.0.3 on 2026-03-16 07:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0002_accountcode_historicalaccountcode_historicalvoucher_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "request_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="결재번호"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "구매품의"),
                            ("EXPENSE", "지출품의"),
                            ("BUDGET", "예산신청"),
                            ("CONTRACT", "계약체결"),
                            ("GENERAL", "일반결재"),
                        ],
                        max_length=20,
                        verbose_name="문서종류",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUBMITTED", "결재요청"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="제출일"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="결재일"),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, verbose_name="반려사유"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결재자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "결재/품의",
                "verbose_name_plural": "결재/품의",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "request_number",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="결재번호"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "구매품의"),
                            ("EXPENSE", "지출품의"),
                            ("BUDGET", "예산신청"),
                            ("CONTRACT", "계약체결"),
                            ("GENERAL", "일반결재"),
                        ],
                        max_length=20,
                        verbose_name="문서종류",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="금액"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성중"),
                            ("SUBMITTED", "결재요청"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                            ("CANCELLED", "취소"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="제출일"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="결재일"),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, verbose_name="반려사유"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결재자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 결재/품의",
                "verbose_name_plural": "historical 결재/품의",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
