# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_approvalrequest_historicalapprovalrequest'),
        ('sales', '0004_order_idx_order_status_order_idx_order_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='idx_approval_status'),
        ),
        migrations.AddIndex(
            model_name='fixedcost',
            index=models.Index(fields=['month'], name='idx_fixedcost_month'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['issue_date'], name='idx_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['invoice_type'], name='idx_invoice_type'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_date'], name='idx_voucher_date'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['approval_status'], name='idx_voucher_approval'),
        ),
    ]
