# Generated by Django 5.2.12 on 2026-03-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_historicalvoucherline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvoucherline',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.voucher', verbose_name='전표'),
        ),
        migrations.AlterField(
            model_name='voucherline',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucher', verbose_name='전표'),
        ),
    ]
