# Generated by Django 5.2.12 on 2026-03-20 14:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_accountpayable_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='계좌별칭')),
                ('account_type', models.CharField(choices=[('PERSONAL', '개인통장'), ('BUSINESS', '사업자통장'), ('PLATFORM', '플랫폼')], max_length=20, verbose_name='계좌유형')),
                ('owner', models.CharField(max_length=50, verbose_name='소유자')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='은행/플랫폼')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본계좌')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '결제계좌',
                'verbose_name_plural': '결제계좌',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='결제계좌'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.bankaccount', verbose_name='결제계좌'),
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='계좌별칭')),
                ('account_type', models.CharField(choices=[('PERSONAL', '개인통장'), ('BUSINESS', '사업자통장'), ('PLATFORM', '플랫폼')], max_length=20, verbose_name='계좌유형')),
                ('owner', models.CharField(max_length=50, verbose_name='소유자')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='은행/플랫폼')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본계좌')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 결제계좌',
                'verbose_name_plural': 'historical 결제계좌',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
