# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_approval_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransfer',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='이체번호'),
        ),
        migrations.AlterField(
            model_name='historicalaccounttransfer',
            name='transfer_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='이체번호'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='입출금번호'),
        ),
        migrations.AlterField(
            model_name='historicaltaxinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='세금계산서번호'),
        ),
        migrations.AlterField(
            model_name='historicalvoucher',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='전표번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='입출금번호'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='세금계산서번호'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='전표번호'),
        ),
    ]
