# Generated by Django 5.2.12 on 2026-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_number_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='recurring_unit',
            field=models.CharField(blank=True, choices=[('WEEKLY', '주'), ('MONTHLY', '월'), ('QUARTERLY', '분기'), ('YEARLY', '년')], default='MONTHLY', max_length=10, verbose_name='반복단위'),
        ),
        migrations.AddField(
            model_name='historicalfixedcost',
            name='recurring_unit',
            field=models.CharField(blank=True, choices=[('WEEKLY', '주'), ('MONTHLY', '월'), ('QUARTERLY', '분기'), ('YEARLY', '년')], default='MONTHLY', max_length=10, verbose_name='반복단위'),
        ),
    ]
