# Generated by Django 5.2.12 on 2026-03-22 04:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_add_recurring_unit'),
        ('inventory', '0010_auto_number_convert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('settlement_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='정산번호')),
                ('period_type', models.CharField(choices=[('MONTHLY', '월'), ('QUARTERLY', '분기'), ('YEARLY', '년')], default='MONTHLY', max_length=10, verbose_name='정산단위')),
                ('period_start', models.DateField(verbose_name='정산 시작일')),
                ('period_end', models.DateField(verbose_name='정산 종료일')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='정산일시')),
                ('total_inventory_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 재고자산')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '원가정산',
                'verbose_name_plural': '원가정산',
                'ordering': ['-period_end', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CostSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stock_quantity', models.IntegerField(verbose_name='재고수량')),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='확정원가')),
                ('inventory_value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='재고자산가액')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='제품')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.costsettlement', verbose_name='정산')),
            ],
            options={
                'verbose_name': '정산항목',
                'verbose_name_plural': '정산항목',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCostSettlement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('settlement_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='정산번호')),
                ('period_type', models.CharField(choices=[('MONTHLY', '월'), ('QUARTERLY', '분기'), ('YEARLY', '년')], default='MONTHLY', max_length=10, verbose_name='정산단위')),
                ('period_start', models.DateField(verbose_name='정산 시작일')),
                ('period_end', models.DateField(verbose_name='정산 종료일')),
                ('settled_at', models.DateTimeField(blank=True, editable=False, verbose_name='정산일시')),
                ('total_inventory_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 재고자산')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 원가정산',
                'verbose_name_plural': 'historical 원가정산',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCostSettlementItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stock_quantity', models.IntegerField(verbose_name='재고수량')),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='확정원가')),
                ('inventory_value', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='재고자산가액')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costsettlement', verbose_name='정산')),
            ],
            options={
                'verbose_name': 'historical 정산항목',
                'verbose_name_plural': 'historical 정산항목',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='costsettlement',
            constraint=models.UniqueConstraint(fields=('period_type', 'period_start', 'period_end'), name='uq_settlement_period'),
        ),
        migrations.AddConstraint(
            model_name='costsettlementitem',
            constraint=models.UniqueConstraint(fields=('settlement', 'product'), name='uq_settlement_product'),
        ),
    ]
