# Generated by Django 5.2.12 on 2026-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_add_cost_settlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costsettlement',
            options={'ordering': ['-settlement_number'], 'verbose_name': '원가정산', 'verbose_name_plural': '원가정산'},
        ),
        migrations.AlterModelOptions(
            name='taxinvoice',
            options={'ordering': ['-invoice_number'], 'verbose_name': '세금계산서', 'verbose_name_plural': '세금계산서'},
        ),
    ]
