# Generated by Django 5.2.12 on 2026-03-22 14:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_costsettlement_options_and_more'),
        ('sales', '0021_historicalorder_is_settled_order_is_settled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesSettlement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('settlement_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='정산번호')),
                ('settlement_date', models.DateField(verbose_name='정산일')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총매출')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총원가')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총부가세')),
                ('total_shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총배송비')),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총이익')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 매출정산',
                'verbose_name_plural': 'historical 매출정산',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('settlement_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='정산번호')),
                ('settlement_date', models.DateField(verbose_name='정산일')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총매출')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총원가')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총부가세')),
                ('total_shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총배송비')),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총이익')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '매출정산',
                'verbose_name_plural': '매출정산',
                'ordering': ['-settlement_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesSettlementOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='매출(공급가)')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='원가')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='부가세')),
                ('shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='배송비')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='이익')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.order', verbose_name='주문')),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.salessettlement', verbose_name='정산')),
            ],
            options={
                'verbose_name': 'historical 매출정산항목',
                'verbose_name_plural': 'historical 매출정산항목',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesSettlementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='매출(공급가)')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='원가')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='부가세')),
                ('shipping', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='배송비')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='이익')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='sales.order', verbose_name='주문')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_orders', to='accounting.salessettlement', verbose_name='정산')),
            ],
            options={
                'verbose_name': '매출정산항목',
                'verbose_name_plural': '매출정산항목',
            },
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='orders',
            field=models.ManyToManyField(related_name='sales_settlements', through='accounting.SalesSettlementOrder', to='sales.order', verbose_name='정산 주문'),
        ),
        migrations.AddConstraint(
            model_name='salessettlementorder',
            constraint=models.UniqueConstraint(fields=('settlement', 'order'), name='uq_settlement_order'),
        ),
    ]
