# Generated by Django 5.2.12 on 2026-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_historicalsalessettlement_salessettlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='total_commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총수수료'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수수료'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='수수료율(%)'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='total_commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총수수료'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수수료'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='수수료율(%)'),
        ),
    ]
