# Generated by Django 5.2.12 on 2026-03-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_historicalsalessettlement_total_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='수수료 지급계좌'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_paid',
            field=models.BooleanField(default=False, verbose_name='수수료 지급완료'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수수료 지급액'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='수수료 지급일'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements', to='accounting.bankaccount', verbose_name='수수료 지급계좌'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_paid',
            field=models.BooleanField(default=False, verbose_name='수수료 지급완료'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='수수료 지급액'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='수수료 지급일'),
        ),
    ]
