# Generated by Django 5.2.12 on 2026-03-22 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_settlement_commission_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='수수료 지급 메모'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.voucher', verbose_name='수수료 전표'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='수수료 지급 메모'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements', to='accounting.voucher', verbose_name='수수료 전표'),
        ),
    ]
