# Generated by Django 5.2.12 on 2026-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_settlement_commission_voucher_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costsettlementitem',
            options={'ordering': ['pk'], 'verbose_name': '정산항목', 'verbose_name_plural': '정산항목'},
        ),
        migrations.AlterModelOptions(
            name='paymentdistribution',
            options={'ordering': ['pk'], 'verbose_name': '결제분배', 'verbose_name_plural': '결제분배'},
        ),
        migrations.AlterModelOptions(
            name='salessettlementorder',
            options={'ordering': ['pk'], 'verbose_name': '매출정산항목', 'verbose_name_plural': '매출정산항목'},
        ),
        migrations.AlterModelOptions(
            name='voucherline',
            options={'ordering': ['pk'], 'verbose_name': '전표항목', 'verbose_name_plural': '전표항목'},
        ),
    ]
