# Generated by Django 5.2.12 on 2026-03-24 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0024_currency_historicalcurrency_historicalexchangerate_and_more",
        ),
        ("sales", "0031_alter_customer_address_alter_customer_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltaxinvoice",
            name="electronic_status",
            field=models.CharField(
                choices=[
                    ("NONE", "미발행"),
                    ("DRAFT", "작성중"),
                    ("ISSUED", "발행완료"),
                    ("SENT", "국세청 전송"),
                    ("ACCEPTED", "국세청 승인"),
                    ("REJECTED", "국세청 반려"),
                    ("CANCELLED", "취소"),
                ],
                default="NONE",
                max_length=15,
                verbose_name="전자발행상태",
            ),
        ),
        migrations.AddField(
            model_name="historicaltaxinvoice",
            name="issue_id",
            field=models.CharField(
                blank=True,
                help_text="전자세금계산서 발행 고유ID",
                max_length=100,
                verbose_name="발행ID",
            ),
        ),
        migrations.AddField(
            model_name="historicaltaxinvoice",
            name="nts_confirmation_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="국세청 승인번호"
            ),
        ),
        migrations.AddField(
            model_name="historicaltaxinvoice",
            name="nts_response",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="국세청 응답"
            ),
        ),
        migrations.AddField(
            model_name="historicaltaxinvoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="전송일시"),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="electronic_status",
            field=models.CharField(
                choices=[
                    ("NONE", "미발행"),
                    ("DRAFT", "작성중"),
                    ("ISSUED", "발행완료"),
                    ("SENT", "국세청 전송"),
                    ("ACCEPTED", "국세청 승인"),
                    ("REJECTED", "국세청 반려"),
                    ("CANCELLED", "취소"),
                ],
                default="NONE",
                max_length=15,
                verbose_name="전자발행상태",
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="issue_id",
            field=models.CharField(
                blank=True,
                help_text="전자세금계산서 발행 고유ID",
                max_length=100,
                verbose_name="발행ID",
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="nts_confirmation_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="국세청 승인번호"
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="nts_response",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="국세청 응답"
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="전송일시"),
        ),
        migrations.AddIndex(
            model_name="taxinvoice",
            index=models.Index(
                fields=["electronic_status"], name="idx_invoice_estatus"
            ),
        ),
    ]
