# Generated by Django 5.2.12 on 2026-03-27 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_add_electronic_invoice_fields'),
        ('hr', '0010_alter_historicalpersonnelaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='급여계좌 연동 시 직원 프로필과 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='hr.employeeprofile', verbose_name='직원'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='employee',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='급여계좌 연동 시 직원 프로필과 연결', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employeeprofile', verbose_name='직원'),
        ),
    ]
