# Generated by Django 5.2.12 on 2026-03-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_bankaccount_employee_historicalbankaccount_employee'),
        ('sales', '0033_historicalpartner_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='거래처 결제계좌 연동', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='sales.partner', verbose_name='거래처'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='거래처 결제계좌 연동', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='거래처'),
        ),
    ]
