# Generated by Django 5.2.12 on 2026-03-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_bankaccount_partner_historicalbankaccount_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, help_text='메인 대시보드에 잔액 표시', verbose_name='대시보드 표시'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='show_on_dashboard',
            field=models.BooleanField(default=False, help_text='메인 대시보드에 잔액 표시', verbose_name='대시보드 표시'),
        ),
    ]
