# Generated by Django 5.2.12 on 2026-03-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_bankaccount_show_on_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='commission_deposit_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='거래처/파트너 입금계좌 (선택)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='수수료 입금계좌'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='commission_deposit_account',
            field=models.ForeignKey(blank=True, help_text='거래처/파트너 입금계좌 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_deposit_settlements', to='accounting.bankaccount', verbose_name='수수료 입금계좌'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlement',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='수수료 출금계좌'),
        ),
        migrations.AlterField(
            model_name='salessettlement',
            name='commission_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements', to='accounting.bankaccount', verbose_name='수수료 출금계좌'),
        ),
    ]
