# Generated by Django 5.2.12 on 2026-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_historicalsalessettlement_commission_deposit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='total_cost_variance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='양수=원가상승(불리), 음수=원가하락(유리)', max_digits=15, verbose_name='총원가차이'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='cost_variance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산시점 원가 - 주문시점 원가 (양수=원가상승)', max_digits=15, verbose_name='원가차이'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='cost_variance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='원가차이율(%)'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='current_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산 생성 시 제품 현재 원가로 자동 측정', max_digits=15, verbose_name='원가(정산시점)'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='total_cost_variance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='양수=원가상승(불리), 음수=원가하락(유리)', max_digits=15, verbose_name='총원가차이'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='cost_variance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산시점 원가 - 주문시점 원가 (양수=원가상승)', max_digits=15, verbose_name='원가차이'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='cost_variance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='원가차이율(%)'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='current_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산 생성 시 제품 현재 원가로 자동 측정', max_digits=15, verbose_name='원가(정산시점)'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlementorder',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='원가(주문시점)'),
        ),
        migrations.AlterField(
            model_name='salessettlementorder',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='원가(주문시점)'),
        ),
    ]
