# Generated by Django 5.2.12 on 2026-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_historicalsalessettlement_total_cost_variance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalessettlement',
            name='total_platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼(네이버, 쿠팡 등)에서 이미 공제된 수수료', max_digits=15, verbose_name='총플랫폼수수료'),
        ),
        migrations.AddField(
            model_name='historicalsalessettlementorder',
            name='platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼에서 이미 공제된 수수료', max_digits=15, verbose_name='플랫폼 수수료'),
        ),
        migrations.AddField(
            model_name='salessettlement',
            name='total_platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼(네이버, 쿠팡 등)에서 이미 공제된 수수료', max_digits=15, verbose_name='총플랫폼수수료'),
        ),
        migrations.AddField(
            model_name='salessettlementorder',
            name='platform_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='플랫폼에서 이미 공제된 수수료', max_digits=15, verbose_name='플랫폼 수수료'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlement',
            name='total_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산 시 수수료율로 추가 계산된 수수료', max_digits=15, verbose_name='총정산수수료'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlementorder',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='정산 수수료'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlementorder',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='정산 수수료율(%)'),
        ),
        migrations.AlterField(
            model_name='salessettlement',
            name='total_commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='정산 시 수수료율로 추가 계산된 수수료', max_digits=15, verbose_name='총정산수수료'),
        ),
        migrations.AlterField(
            model_name='salessettlementorder',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='정산 수수료'),
        ),
        migrations.AlterField(
            model_name='salessettlementorder',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='정산 수수료율(%)'),
        ),
    ]
