# Generated by Django 5.2.12 on 2026-04-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_split_platform_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalessettlement',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총공급가액'),
        ),
        migrations.AlterField(
            model_name='historicalsalessettlementorder',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='공급가액'),
        ),
        migrations.AlterField(
            model_name='salessettlement',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총공급가액'),
        ),
        migrations.AlterField(
            model_name='salessettlementorder',
            name='revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='공급가액'),
        ),
    ]
