# Generated by Django 5.2.12 on 2026-04-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_historicalsalessettlement_total_revenue_and_more'),
        ('purchase', '0015_goodsreceiptitem_asset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='purchase.purchaseorder', verbose_name='발주서'),
        ),
        migrations.AddField(
            model_name='historicalaccountpayable',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorder', verbose_name='발주서'),
        ),
    ]
