# Generated by Django 5.2.12 on 2026-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_cardbilling_creditcard_cardtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('OPERATING', '영업활동'), ('INVESTING', '투자활동'), ('FINANCING', '재무활동')], default='', max_length=20, verbose_name='현금흐름 분류'),
        ),
        migrations.AddField(
            model_name='historicalaccountcode',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('OPERATING', '영업활동'), ('INVESTING', '투자활동'), ('FINANCING', '재무활동')], default='', max_length=20, verbose_name='현금흐름 분류'),
        ),
    ]
