# Generated by Django 5.2.12 on 2026-04-11 03:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_accountcode_cash_flow_category_and_more'),
        ('hr', '0012_historicallaborconfig_historicalseverancepay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='센터명')),
                ('center_type', models.CharField(choices=[('COST', '원가센터'), ('PROFIT', '이익센터'), ('INVESTMENT', '투자센터')], default='COST', max_length=20, verbose_name='센터유형')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='부서')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='책임자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.costcenter', verbose_name='상위센터')),
            ],
            options={
                'verbose_name': '원가센터',
                'verbose_name_plural': '원가센터',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='historicalvoucherline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costcenter', verbose_name='원가센터'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='원가센터'),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='위젯명')),
                ('widget_type', models.CharField(choices=[('CHART', '차트'), ('TABLE', '테이블'), ('KPI', 'KPI'), ('PIVOT', '피벗')], max_length=20, verbose_name='위젯유형')),
                ('config', models.JSONField(default=dict, verbose_name='설정')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시여부')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대시보드 위젯',
                'verbose_name_plural': '대시보드 위젯',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCostCenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='센터명')),
                ('center_type', models.CharField(choices=[('COST', '원가센터'), ('PROFIT', '이익센터'), ('INVESTMENT', '투자센터')], default='COST', max_length=20, verbose_name='센터유형')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.department', verbose_name='부서')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='책임자')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costcenter', verbose_name='상위센터')),
            ],
            options={
                'verbose_name': 'historical 원가센터',
                'verbose_name_plural': 'historical 원가센터',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDashboardWidget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='위젯명')),
                ('widget_type', models.CharField(choices=[('CHART', '차트'), ('TABLE', '테이블'), ('KPI', 'KPI'), ('PIVOT', '피벗')], max_length=20, verbose_name='위젯유형')),
                ('config', models.JSONField(default=dict, verbose_name='설정')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시여부')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'historical 대시보드 위젯',
                'verbose_name_plural': 'historical 대시보드 위젯',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
