# Generated by Django 5.2.12 on 2026-04-15 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_bankconnection_bankstatement_banktransaction_company_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['account', 'year', 'month'], name='idx_budget_acct_yr_mo'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', 'transaction_date'], name='idx_cardtx_card_date'),
        ),
        migrations.AddIndex(
            model_name='salessettlement',
            index=models.Index(fields=['settlement_date'], name='idx_settlement_date'),
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['account', 'voucher'], name='idx_voucherline_acct_vch'),
        ),
    ]
