# Generated by Django 5.2.12 on 2026-04-20 13:44

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_budget_idx_budget_acct_yr_mo_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCashReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='현금영수증 승인번호')),
                ('issued_at', models.DateTimeField(verbose_name='발행일시')),
                ('supply_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('purpose', models.CharField(choices=[('INDIVIDUAL', '소득공제용'), ('BUSINESS', '지출증빙용')], default='INDIVIDUAL', max_length=20, verbose_name='발행목적')),
                ('identifier', models.CharField(help_text='개인: 휴대폰번호/주민번호 뒤6자리, 사업자: 사업자등록번호', max_length=20, verbose_name='식별번호')),
                ('status', models.CharField(choices=[('ISSUED', '발행완료'), ('CANCELLED', '취소')], default='ISSUED', max_length=20, verbose_name='상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='취소사유')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='연관문서ID')),
                ('hometax_key', models.CharField(blank=True, help_text='홈택스 API 연동용 식별자 (향후)', max_length=100, verbose_name='홈택스 키')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='연관문서유형')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 현금영수증',
                'verbose_name_plural': 'historical 현금영수증',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('receipt_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='현금영수증 승인번호')),
                ('issued_at', models.DateTimeField(verbose_name='발행일시')),
                ('supply_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('purpose', models.CharField(choices=[('INDIVIDUAL', '소득공제용'), ('BUSINESS', '지출증빙용')], default='INDIVIDUAL', max_length=20, verbose_name='발행목적')),
                ('identifier', models.CharField(help_text='개인: 휴대폰번호/주민번호 뒤6자리, 사업자: 사업자등록번호', max_length=20, verbose_name='식별번호')),
                ('status', models.CharField(choices=[('ISSUED', '발행완료'), ('CANCELLED', '취소')], default='ISSUED', max_length=20, verbose_name='상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='취소사유')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='연관문서ID')),
                ('hometax_key', models.CharField(blank=True, help_text='홈택스 API 연동용 식별자 (향후)', max_length=100, verbose_name='홈택스 키')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='연관문서유형')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '현금영수증',
                'verbose_name_plural': '현금영수증',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['status'], name='idx_cashreceipt_status'), models.Index(fields=['issued_at'], name='idx_cashreceipt_issued'), models.Index(fields=['content_type', 'object_id'], name='idx_cashreceipt_gfk')],
            },
        ),
    ]
