# Generated by Django 5.2.12 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_cashreceiptitem_historicalcashreceiptitem'),
        ('sales', '0047_order_shipping_charged'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='source_orders',
            field=models.ManyToManyField(blank=True, related_name='cash_receipts_linked', to='sales.order', verbose_name='연결된 주문'),
        ),
    ]
