# Generated by Django 5.2.12 on 2026-04-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_add_baddebtallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='issuer_type',
            field=models.CharField(choices=[('SELF', '자사발행'), ('PLATFORM', '플랫폼대행'), ('OUTSOURCED', '세무사대행')], default='SELF', max_length=16, verbose_name='발행주체'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='platform_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='대행플랫폼'),
        ),
        migrations.AddField(
            model_name='historicalcashreceipt',
            name='issuer_type',
            field=models.CharField(choices=[('SELF', '자사발행'), ('PLATFORM', '플랫폼대행'), ('OUTSOURCED', '세무사대행')], default='SELF', max_length=16, verbose_name='발행주체'),
        ),
        migrations.AddField(
            model_name='historicalcashreceipt',
            name='platform_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='대행플랫폼'),
        ),
        migrations.AddField(
            model_name='historicaltaxinvoice',
            name='issuer_type',
            field=models.CharField(choices=[('SELF', '자사발행'), ('PLATFORM', '플랫폼대행'), ('OUTSOURCED', '세무사대행')], default='SELF', max_length=16, verbose_name='발행주체'),
        ),
        migrations.AddField(
            model_name='historicaltaxinvoice',
            name='platform_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='대행플랫폼'),
        ),
        migrations.AddField(
            model_name='historicaltaxinvoice',
            name='tax_type',
            field=models.CharField(choices=[('TAXABLE', '과세'), ('ZERO_RATE', '영세율(수출)'), ('EXEMPT', '면세')], default='TAXABLE', max_length=16, verbose_name='과세구분'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='issuer_type',
            field=models.CharField(choices=[('SELF', '자사발행'), ('PLATFORM', '플랫폼대행'), ('OUTSOURCED', '세무사대행')], default='SELF', max_length=16, verbose_name='발행주체'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='platform_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='대행플랫폼'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='tax_type',
            field=models.CharField(choices=[('TAXABLE', '과세'), ('ZERO_RATE', '영세율(수출)'), ('EXEMPT', '면세')], default='TAXABLE', max_length=16, verbose_name='과세구분'),
        ),
    ]
