# Generated by Django 5.2.12 on 2026-04-24 15:14

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_cashreceipt_issuer_type_cashreceipt_platform_name_and_more'),
        ('sales', '0049_historicalorder_accounting_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxinvoice',
            name='vat_deduction_type',
            field=models.CharField(choices=[('DEDUCTIBLE', '일반매입(공제)'), ('DEEMED', '의제매입세액(면세 농축수산물)'), ('NON_DEDUCTIBLE', '공제받지못할매입')], default='DEDUCTIBLE', help_text='invoice_type=PURCHASE 에만 유효. 부가세 신고 매입측 집계 구분.', max_length=20, verbose_name='매입세액 구분'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='vat_deduction_type',
            field=models.CharField(choices=[('DEDUCTIBLE', '일반매입(공제)'), ('DEEMED', '의제매입세액(면세 농축수산물)'), ('NON_DEDUCTIBLE', '공제받지못할매입')], default='DEDUCTIBLE', help_text='invoice_type=PURCHASE 에만 유효. 부가세 신고 매입측 집계 구분.', max_length=20, verbose_name='매입세액 구분'),
        ),
        migrations.CreateModel(
            name='HistoricalCardSalesSlip',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('slip_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='매출전표번호')),
                ('approved_at', models.DateTimeField(verbose_name='승인일시')),
                ('approval_code', models.CharField(help_text='카드사 승인 시 발급되는 고유 번호', max_length=32, verbose_name='카드승인번호')),
                ('card_brand', models.CharField(choices=[('VISA', 'VISA'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express'), ('JCB', 'JCB'), ('UNION', 'UnionPay'), ('DOMESTIC', '국내카드'), ('OTHER', '기타')], default='DOMESTIC', max_length=16, verbose_name='카드사')),
                ('card_number_masked', models.CharField(help_text='4-****-****-1234 포맷. 평문 저장 금지.', max_length=32, verbose_name='카드번호(마스킹)')),
                ('merchant_number', models.CharField(blank=True, max_length=32, verbose_name='가맹점번호')),
                ('supply_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('status', models.CharField(choices=[('APPROVED', '승인'), ('CANCELLED', '취소')], default='APPROVED', max_length=20, verbose_name='상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='취소사유')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.cardtransaction', verbose_name='카드거래')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.order', verbose_name='주문')),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 카드매출전표',
                'verbose_name_plural': 'historical 카드매출전표',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CardSalesSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('slip_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='매출전표번호')),
                ('approved_at', models.DateTimeField(verbose_name='승인일시')),
                ('approval_code', models.CharField(help_text='카드사 승인 시 발급되는 고유 번호', max_length=32, verbose_name='카드승인번호')),
                ('card_brand', models.CharField(choices=[('VISA', 'VISA'), ('MASTER', 'Mastercard'), ('AMEX', 'American Express'), ('JCB', 'JCB'), ('UNION', 'UnionPay'), ('DOMESTIC', '국내카드'), ('OTHER', '기타')], default='DOMESTIC', max_length=16, verbose_name='카드사')),
                ('card_number_masked', models.CharField(help_text='4-****-****-1234 포맷. 평문 저장 금지.', max_length=32, verbose_name='카드번호(마스킹)')),
                ('merchant_number', models.CharField(blank=True, max_length=32, verbose_name='가맹점번호')),
                ('supply_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='부가세')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('status', models.CharField(choices=[('APPROVED', '승인'), ('CANCELLED', '취소')], default='APPROVED', max_length=20, verbose_name='상태')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='취소사유')),
                ('card_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_slips', to='accounting.cardtransaction', verbose_name='카드거래')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_sales_slips', to='sales.order', verbose_name='주문')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_sales_slips', to='sales.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '카드매출전표',
                'verbose_name_plural': '카드매출전표',
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['approved_at'], name='idx_cardslip_approved'), models.Index(fields=['approval_code'], name='idx_cardslip_approval'), models.Index(fields=['status'], name='idx_cardslip_status')],
            },
        ),
    ]
