# Generated by Django 5.2.12 on 2026-04-25 10:03

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_historicaltaxinvoice_vat_deduction_type_and_more'),
        ('sales', '0050_historicalorder_progress_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='규칙명')),
                ('priority', models.PositiveIntegerField(default=100, help_text='작을수록 먼저 평가', verbose_name='우선순위')),
                ('match_field', models.CharField(choices=[('DEPOSITOR_NAME', '입금자명'), ('AMOUNT_EXACT', '금액 정확일치'), ('AMOUNT_RANGE', '금액 범위'), ('REFERENCE', '적요/메모')], default='DEPOSITOR_NAME', max_length=24, verbose_name='매칭 기준')),
                ('pattern', models.CharField(help_text='입금자명/적요 substring (대소문자 무시), 금액은 숫자', max_length=200, verbose_name='매칭 패턴')),
                ('amount_tolerance', models.DecimalField(decimal_places=0, default=0, help_text='AMOUNT_RANGE 시 ±오차', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액 허용오차')),
                ('date_tolerance_days', models.PositiveIntegerField(default=3, verbose_name='일자 허용 오차(일)')),
                ('is_active_rule', models.BooleanField(default=True, verbose_name='규칙 활성')),
                ('bank_account', models.ForeignKey(blank=True, help_text='공란 시 모든 계좌', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_rules', to='accounting.bankaccount', verbose_name='적용 계좌')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('target_partner', models.ForeignKey(blank=True, help_text='매칭 시 자동 연결할 거래처', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.partner', verbose_name='대상 거래처')),
            ],
            options={
                'verbose_name': '은행거래 매칭규칙',
                'verbose_name_plural': '은행거래 매칭규칙',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardReconRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='규칙명')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='우선순위')),
                ('merchant_pattern', models.CharField(blank=True, help_text='가맹점명 substring (대소문자 무시)', max_length=200, verbose_name='가맹점 패턴')),
                ('is_active_rule', models.BooleanField(default=True, verbose_name='규칙 활성')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_rules', to='accounting.creditcard', verbose_name='적용 카드')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('target_account', models.ForeignKey(blank=True, help_text='매칭 시 자동 분개할 비용 계정', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountcode', verbose_name='대상 계정')),
                ('target_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.partner', verbose_name='대상 거래처')),
            ],
            options={
                'verbose_name': '카드거래 매칭규칙',
                'verbose_name_plural': '카드거래 매칭규칙',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankReconRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='규칙명')),
                ('priority', models.PositiveIntegerField(default=100, help_text='작을수록 먼저 평가', verbose_name='우선순위')),
                ('match_field', models.CharField(choices=[('DEPOSITOR_NAME', '입금자명'), ('AMOUNT_EXACT', '금액 정확일치'), ('AMOUNT_RANGE', '금액 범위'), ('REFERENCE', '적요/메모')], default='DEPOSITOR_NAME', max_length=24, verbose_name='매칭 기준')),
                ('pattern', models.CharField(help_text='입금자명/적요 substring (대소문자 무시), 금액은 숫자', max_length=200, verbose_name='매칭 패턴')),
                ('amount_tolerance', models.DecimalField(decimal_places=0, default=0, help_text='AMOUNT_RANGE 시 ±오차', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='금액 허용오차')),
                ('date_tolerance_days', models.PositiveIntegerField(default=3, verbose_name='일자 허용 오차(일)')),
                ('is_active_rule', models.BooleanField(default=True, verbose_name='규칙 활성')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, help_text='공란 시 모든 계좌', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount', verbose_name='적용 계좌')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_partner', models.ForeignKey(blank=True, db_constraint=False, help_text='매칭 시 자동 연결할 거래처', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='대상 거래처')),
            ],
            options={
                'verbose_name': 'historical 은행거래 매칭규칙',
                'verbose_name_plural': 'historical 은행거래 매칭규칙',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCardReconRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='규칙명')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='우선순위')),
                ('merchant_pattern', models.CharField(blank=True, help_text='가맹점명 substring (대소문자 무시)', max_length=200, verbose_name='가맹점 패턴')),
                ('is_active_rule', models.BooleanField(default=True, verbose_name='규칙 활성')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.creditcard', verbose_name='적용 카드')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, db_constraint=False, help_text='매칭 시 자동 분개할 비용 계정', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.accountcode', verbose_name='대상 계정')),
                ('target_partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.partner', verbose_name='대상 거래처')),
            ],
            options={
                'verbose_name': 'historical 카드거래 매칭규칙',
                'verbose_name_plural': 'historical 카드거래 매칭규칙',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVoucherApprovalConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('auto_voucher_default_status', models.CharField(choices=[('DRAFT', 'DRAFT (작성중)'), ('SUBMITTED', 'SUBMITTED (제출)'), ('APPROVED', 'APPROVED (즉시 승인)')], default='APPROVED', help_text='시그널 자동생성 전표의 기본 승인상태', max_length=15, verbose_name='자동전표 기본상태')),
                ('auto_approval_amount_threshold', models.DecimalField(decimal_places=0, default=0, help_text='이 금액 초과 시 자동전표도 SUBMITTED 강제 (0=한도없음)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='자동승인 금액한도')),
                ('manual_approval_amount_threshold', models.DecimalField(decimal_places=0, default=0, help_text='수동 입력 전표가 이 금액 초과 시 ApprovalRequest 자동생성', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수동전표 결재필수 한도')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 전표 승인 정책',
                'verbose_name_plural': 'historical 전표 승인 정책',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VoucherApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('auto_voucher_default_status', models.CharField(choices=[('DRAFT', 'DRAFT (작성중)'), ('SUBMITTED', 'SUBMITTED (제출)'), ('APPROVED', 'APPROVED (즉시 승인)')], default='APPROVED', help_text='시그널 자동생성 전표의 기본 승인상태', max_length=15, verbose_name='자동전표 기본상태')),
                ('auto_approval_amount_threshold', models.DecimalField(decimal_places=0, default=0, help_text='이 금액 초과 시 자동전표도 SUBMITTED 강제 (0=한도없음)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='자동승인 금액한도')),
                ('manual_approval_amount_threshold', models.DecimalField(decimal_places=0, default=0, help_text='수동 입력 전표가 이 금액 초과 시 ApprovalRequest 자동생성', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수동전표 결재필수 한도')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '전표 승인 정책',
                'verbose_name_plural': '전표 승인 정책',
            },
        ),
    ]
