# Generated by Django 5.2.12 on 2026-04-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_bankreconrule_cardreconrule_historicalbankreconrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='pl_bucket',
            field=models.CharField(blank=True, choices=[('SALES', '매출'), ('COGS', '매출원가'), ('SGA', '판매비와관리비'), ('NONOP_REVENUE', '영업외수익'), ('NONOP_EXPENSE', '영업외비용'), ('INCOME_TAX', '법인세')], default='', help_text='K-GAAP 9단계 손익계산서 분류 — 공란이면 손익계산서에서 제외', max_length=20, verbose_name='손익계산서 분류'),
        ),
        migrations.AddField(
            model_name='historicalaccountcode',
            name='pl_bucket',
            field=models.CharField(blank=True, choices=[('SALES', '매출'), ('COGS', '매출원가'), ('SGA', '판매비와관리비'), ('NONOP_REVENUE', '영업외수익'), ('NONOP_EXPENSE', '영업외비용'), ('INCOME_TAX', '법인세')], default='', help_text='K-GAAP 9단계 손익계산서 분류 — 공란이면 손익계산서에서 제외', max_length=20, verbose_name='손익계산서 분류'),
        ),
    ]
