# Generated by Django 5.2.12 on 2026-04-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_accountcode_pl_bucket_and_more'),
        ('localizations', '0002_seed_kr_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='country',
            field=models.ForeignKey(blank=True, help_text='계정과목 적용 국가 (다국가 모드용)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='historicalaccountcode',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='계정과목 적용 국가 (다국가 모드용)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='historicaltaxrate',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='세율 적용 국가 (다국가 모드용)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='country',
            field=models.ForeignKey(blank=True, help_text='세율 적용 국가 (다국가 모드용)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='localizations.country', verbose_name='국가'),
        ),
    ]
