# Generated by Django 5.2.12 on 2026-04-30 02:36

import apps.localizations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_alter_historicalintercompanytransaction_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(default=apps.localizations.get_default_country_code, max_length=5, verbose_name='국가코드'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='country_code',
            field=models.CharField(default=apps.localizations.get_default_country_code, max_length=5, verbose_name='국가코드'),
        ),
    ]
