# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_forecasts', to='inventory.product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='forecastparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_parameters', to='inventory.product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='soplineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sop_line_items', to='inventory.product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='soplineitem',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='forecast.sopscenario', verbose_name='시나리오'),
        ),
        migrations.AlterField(
            model_name='sopscenario',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='forecast.sopmeeting', verbose_name='회의'),
        ),
    ]
