# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_demandforecast_product_and_more'),
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['product', 'period_start'], name='idx_forecast_product_period'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['forecast_method', 'period_start'], name='idx_forecast_method_period'),
        ),
        migrations.AddIndex(
            model_name='sopmeeting',
            index=models.Index(fields=['status', 'meeting_date'], name='idx_sop_status_date'),
        ),
    ]
