# Generated by Django 5.2.12 on 2026-04-12 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleattachment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='wiki.wikiarticle', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='wiki.wikiarticle', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='wiki.wikiarticle', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='wiki.wikispace', verbose_name='공간'),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='wiki.wikispace', verbose_name='공간'),
        ),
    ]
