# Generated by Django 6.0.3 on 2026-03-16 06:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_historicalstocktransfer_stocktransfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProductRegistration",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "serial_number",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="시리얼번호"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="고객명"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="구매일")),
                (
                    "purchase_channel",
                    models.CharField(
                        blank=True,
                        help_text="스마트스토어, 공식홈페이지, 오프라인 등",
                        max_length=100,
                        verbose_name="구매처",
                    ),
                ),
                ("warranty_start", models.DateField(verbose_name="보증시작일")),
                ("warranty_end", models.DateField(verbose_name="보증만료일")),
                (
                    "photo",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="인증사진"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증완료"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 정품등록",
                "verbose_name_plural": "historical 정품등록",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProductRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="시리얼번호"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="고객명"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="구매일")),
                (
                    "purchase_channel",
                    models.CharField(
                        blank=True,
                        help_text="스마트스토어, 공식홈페이지, 오프라인 등",
                        max_length=100,
                        verbose_name="구매처",
                    ),
                ),
                ("warranty_start", models.DateField(verbose_name="보증시작일")),
                ("warranty_end", models.DateField(verbose_name="보증만료일")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="warranty/",
                        verbose_name="인증사진",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증완료"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "정품등록",
                "verbose_name_plural": "정품등록",
                "ordering": ["-purchase_date"],
            },
        ),
    ]
