# Generated by Django 5.2.12 on 2026-03-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_order_options_alter_quotation_options_and_more'),
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregistration',
            options={'ordering': ['-pk'], 'verbose_name': '정품등록', 'verbose_name_plural': '정품등록'},
        ),
        migrations.AddField(
            model_name='historicalproductregistration',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer', verbose_name='고객'),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_registrations', to='sales.customer', verbose_name='고객'),
        ),
    ]
