# Generated by Django 5.2.12 on 2026-03-24 02:02

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warranty", "0002_alter_productregistration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproductregistration",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductregistration",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="연락처"
            ),
        ),
        migrations.AlterField(
            model_name="productregistration",
            name="email",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="productregistration",
            name="phone",
            field=apps.core.fields.EncryptedCharField(
                max_length=500, verbose_name="연락처"
            ),
        ),
    ]
