# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_alter_historicalproductregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.storage.hashed_upload_path('warranty'), verbose_name='인증사진'),
        ),
    ]
