# Generated by Django 5.2.12 on 2026-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_alter_productregistration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductregistration',
            name='custom_info',
            field=models.BooleanField(default=False, verbose_name='고객 정보와 다름'),
        ),
        migrations.AddField(
            model_name='historicalproductregistration',
            name='verified_warranty_days',
            field=models.PositiveIntegerField(default=730, help_text='인증 완료 시 적용되는 AS기간. 생성 후 수동 변경 가능.', verbose_name='인증 후 AS기간(일)'),
        ),
        migrations.AddField(
            model_name='historicalproductregistration',
            name='warranty_days',
            field=models.PositiveIntegerField(default=365, help_text='정품등록 시 기본 AS기간. 생성 후 수동 변경 가능.', verbose_name='AS기간(일)'),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='custom_info',
            field=models.BooleanField(default=False, verbose_name='고객 정보와 다름'),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='verified_warranty_days',
            field=models.PositiveIntegerField(default=730, help_text='인증 완료 시 적용되는 AS기간. 생성 후 수동 변경 가능.', verbose_name='인증 후 AS기간(일)'),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='warranty_days',
            field=models.PositiveIntegerField(default=365, help_text='정품등록 시 기본 AS기간. 생성 후 수동 변경 가능.', verbose_name='AS기간(일)'),
        ),
    ]
