# Generated by Django 5.2.12 on 2026-04-15 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        ('warranty', '0005_historicalproductregistration_custom_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['is_verified'], name='idx_prodreg_verified'),
        ),
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['purchase_date'], name='idx_prodreg_purchase'),
        ),
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['warranty_end'], name='idx_prodreg_wend'),
        ),
        migrations.AddIndex(
            model_name='productregistration',
            index=models.Index(fields=['is_verified', 'warranty_end'], name='idx_prodreg_ver_wend'),
        ),
    ]
