# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        ('purchase', '0016_historicalrfq_historicalvendorscore_rfq_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='wms.warehousezone', verbose_name='구역'),
        ),
        migrations.AlterField(
            model_name='pickorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_orders', to='sales.order', verbose_name='주문'),
        ),
        migrations.AlterField(
            model_name='pickorderitem',
            name='pick_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wms.pickorder', verbose_name='피킹오더'),
        ),
        migrations.AlterField(
            model_name='pickorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_order_items', to='inventory.product', verbose_name='품목'),
        ),
        migrations.AlterField(
            model_name='putawaytask',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='putaway_tasks', to='purchase.goodsreceipt', verbose_name='입고'),
        ),
        migrations.AlterField(
            model_name='putawaytask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='putaway_tasks', to='inventory.product', verbose_name='품목'),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='inventory.warehouse', verbose_name='창고'),
        ),
    ]
