# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_serialnumber_idx_serial_status_date_and_more'),
        ('purchase', '0017_goodsreceipt_idx_gr_receipt_date_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        ('wms', '0002_alter_binlocation_zone_alter_pickorder_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['status', 'created_at'], name='idx_pick_status_date'),
        ),
        migrations.AddIndex(
            model_name='pickorder',
            index=models.Index(fields=['status', 'priority'], name='idx_pick_status_priority'),
        ),
        migrations.AddIndex(
            model_name='putawaytask',
            index=models.Index(fields=['status', 'created_at'], name='idx_putaway_status_date'),
        ),
        migrations.AddIndex(
            model_name='warehousezone',
            index=models.Index(fields=['warehouse', 'zone_type'], name='idx_zone_warehouse_type'),
        ),
        migrations.AddIndex(
            model_name='waveplan',
            index=models.Index(fields=['status', 'created_at'], name='idx_wave_status_date'),
        ),
    ]
