# Generated by Django 5.2.12 on 2026-04-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_driver_user_alter_freightcost_route_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'sequence')},
        ),
    ]
