# Generated by Django 5.2.12 on 2026-04-12 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='lms.courseenrollment', verbose_name='수강등록'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='수강자'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lms.course', verbose_name='강좌'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_progresses', to='lms.courseenrollment', verbose_name='수강등록'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresses', to='lms.lesson', verbose_name='강의'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='lms.course', verbose_name='강좌'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='lms.courseenrollment', verbose_name='수강등록'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='lms.quizquestion', verbose_name='문제'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='lms.quiz', verbose_name='퀴즈'),
        ),
    ]
