# Generated by Django 6.0.3 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="원가"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="원가"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="판매단가"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="판매단가"
            ),
        ),
    ]
