# Generated by Django 6.0.3 on 2026-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_historicalproduct_cost_price_product_cost_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstockmovement",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="수량"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="수량"),
        ),
    ]
