# Generated by Django 6.0.3 on 2026-03-16 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalstocktransfer_stocktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='idx_product_type_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_stock'], name='idx_product_stock'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='idx_movement_type'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_date'], name='idx_movement_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_type'], name='idx_mv_product_type'),
        ),
    ]
