# Generated by Django 5.2.12 on 2026-03-19 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_stock_non_negative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="원가",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="판매단가",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockmovement",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="원가",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="판매단가",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="단가",
            ),
        ),
    ]
