# Generated by Django 5.2.12 on 2026-03-19 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_historicalproduct_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_date'], name='idx_transfer_date'),
        ),
    ]
