# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktransfer_idx_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='movement_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='전표번호'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='transfer_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='이동번호'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='전표번호'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='이동번호'),
        ),
    ]
