# Generated by Django 5.2.12 on 2026-03-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_number_convert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-movement_number'], 'verbose_name': '입출고', 'verbose_name_plural': '입출고'},
        ),
    ]
