# Generated by Django 5.2.12 on 2026-03-22 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_record_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='현재고'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='참조'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='현재고'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='참조'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량'),
        ),
    ]
