# Generated by Django 5.2.12 on 2026-03-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_historicalproduct_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본창고'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본창고'),
        ),
    ]
