# Generated by Django 5.2.12 on 2026-03-23 03:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_historicalwarehouse_is_default_warehouse_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockCount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('count_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='실사번호')),
                ('count_date', models.DateField(verbose_name='실사일')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('IN_PROGRESS', '실사중'), ('COMPLETED', '완료'), ('ADJUSTED', '조정완료')], default='DRAFT', max_length=15, verbose_name='상태')),
                ('description', models.TextField(blank=True, verbose_name='비고')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': 'historical 재고실사',
                'verbose_name_plural': 'historical 재고실사',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('count_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='실사번호')),
                ('count_date', models.DateField(verbose_name='실사일')),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('IN_PROGRESS', '실사중'), ('COMPLETED', '완료'), ('ADJUSTED', '조정완료')], default='DRAFT', max_length=15, verbose_name='상태')),
                ('description', models.TextField(blank=True, verbose_name='비고')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '재고실사',
                'verbose_name_plural': '재고실사',
                'ordering': ['-count_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockCountItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='시스템재고')),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='실사재고')),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='차이')),
                ('adjusted', models.BooleanField(default=False, verbose_name='조정완료')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('stock_count', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockcount', verbose_name='재고실사')),
            ],
            options={
                'verbose_name': 'historical 재고실사항목',
                'verbose_name_plural': 'historical 재고실사항목',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='시스템재고')),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='실사재고')),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='차이')),
                ('adjusted', models.BooleanField(default=False, verbose_name='조정완료')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='제품')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount', verbose_name='재고실사')),
            ],
            options={
                'verbose_name': '재고실사항목',
                'verbose_name_plural': '재고실사항목',
                'ordering': ['pk'],
            },
        ),
    ]
