# Generated by Django 5.2.12 on 2026-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='주문~입고 평균 소요일', verbose_name='조달리드타임(일)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='주문~입고 평균 소요일', verbose_name='조달리드타임(일)'),
        ),
    ]
