# Generated by Django 5.2.12 on 2026-03-23 08:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_historicalproduct_lead_time_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='reserved_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='예약재고'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valuation_method',
            field=models.CharField(choices=[('AVG', '이동평균법'), ('FIFO', '선입선출법'), ('LIFO', '후입선출법')], default='AVG', max_length=5, verbose_name='재고평가법'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='예약재고'),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('AVG', '이동평균법'), ('FIFO', '선입선출법'), ('LIFO', '후입선출법')], default='AVG', max_length=5, verbose_name='재고평가법'),
        ),
        migrations.CreateModel(
            name='HistoricalStockLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('lot_number', models.CharField(db_index=True, max_length=50, verbose_name='LOT번호')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='초기입고량')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='잔여수량')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='입고단가')),
                ('received_date', models.DateField(verbose_name='입고일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유효기한')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('stock_movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmovement', verbose_name='입고전표')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': 'historical 재고 LOT',
                'verbose_name_plural': 'historical 재고 LOT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='LOT번호')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='초기입고량')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='잔여수량')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='입고단가')),
                ('received_date', models.DateField(verbose_name='입고일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='유효기한')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product', verbose_name='제품')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.stockmovement', verbose_name='입고전표')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '재고 LOT',
                'verbose_name_plural': '재고 LOT',
                'ordering': ['received_date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='historicalstockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stocklot', verbose_name='LOT'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocklot', verbose_name='LOT'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='lot_remaining_non_negative'),
        ),
    ]
