# Generated by Django 5.2.12 on 2026-03-23 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_historicalproduct_reserved_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_stock__gte', 0)), name='reserved_stock_non_negative'),
        ),
    ]
