# Generated by Django 5.2.12 on 2026-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='location',
            field=models.CharField(blank=True, help_text='동/층/구역 등 상세 위치', max_length=200, verbose_name='상세위치'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, help_text='동/층/구역 등 상세 위치', max_length=200, verbose_name='상세위치'),
        ),
    ]
