# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_historicalwarehouse_address_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='제품코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='제품코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.storage.hashed_upload_path('products'), verbose_name='이미지'),
        ),
    ]
