# Generated by Django 5.2.12 on 2026-04-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_historicalproduct_code_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(choices=[('RAW', '원자재'), ('SEMI', '반제품'), ('FINISHED', '완제품'), ('SERVICE', '서비스'), ('INTANGIBLE', '무형상품')], default='FINISHED', max_length=10, verbose_name='제품유형'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('RAW', '원자재'), ('SEMI', '반제품'), ('FINISHED', '완제품'), ('SERVICE', '서비스'), ('INTANGIBLE', '무형상품')], default='FINISHED', max_length=10, verbose_name='제품유형'),
        ),
    ]
