# Generated by Django 5.2.12 on 2026-04-10 04:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_historicalproduct_product_type_and_more'),
        ('production', '0014_historicalproductionrecord_actual_labor_cost_and_more'),
        ('sales', '0045_historicalpartner_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='serial_prefix',
            field=models.CharField(blank=True, default='', help_text='예: SN-PRD001-', max_length=20, verbose_name='시리얼접두사'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='serial_tracking',
            field=models.BooleanField(default=False, help_text='활성화 시 생산 완료 시 자동으로 시리얼번호 생성', verbose_name='시리얼추적'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_prefix',
            field=models.CharField(blank=True, default='', help_text='예: SN-PRD001-', max_length=20, verbose_name='시리얼접두사'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_tracking',
            field=models.BooleanField(default=False, help_text='활성화 시 생산 완료 시 자동으로 시리얼번호 생성', verbose_name='시리얼추적'),
        ),
        migrations.CreateModel(
            name='HistoricalSerialNumber',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('serial', models.CharField(db_index=True, max_length=100, verbose_name='시리얼번호')),
                ('status', models.CharField(choices=[('PRODUCED', '생산완료'), ('IN_STOCK', '재고'), ('RESERVED', '예약'), ('SHIPPED', '출고'), ('RETURNED', '반품'), ('DISPOSED', '폐기')], default='IN_STOCK', max_length=20, verbose_name='상태')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='생산일')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='출고일')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='제품')),
                ('production_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionrecord', verbose_name='생산기록')),
                ('shipment_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.shipmentitem', verbose_name='출고항목')),
                ('stock_lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stocklot', verbose_name='재고LOT')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='보관창고')),
            ],
            options={
                'verbose_name': 'historical 시리얼번호',
                'verbose_name_plural': 'historical 시리얼번호',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('serial', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='시리얼번호')),
                ('status', models.CharField(choices=[('PRODUCED', '생산완료'), ('IN_STOCK', '재고'), ('RESERVED', '예약'), ('SHIPPED', '출고'), ('RETURNED', '반품'), ('DISPOSED', '폐기')], default='IN_STOCK', max_length=20, verbose_name='상태')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='생산일')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='출고일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.product', verbose_name='제품')),
                ('production_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='production.productionrecord', verbose_name='생산기록')),
                ('shipment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='sales.shipmentitem', verbose_name='출고항목')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.stocklot', verbose_name='재고LOT')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.warehouse', verbose_name='보관창고')),
            ],
            options={
                'verbose_name': '시리얼번호',
                'verbose_name_plural': '시리얼번호',
                'ordering': ['-created_at'],
            },
        ),
    ]
