# Generated by Django 5.2.12 on 2026-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_historicalproduct_serial_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0, help_text='현재고가 이 수량 이하이면 발주 알림', verbose_name='재주문점'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0, help_text='현재고가 이 수량 이하이면 발주 알림', verbose_name='재주문점'),
        ),
    ]
