# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_historicalproduct_reorder_point_and_more'),
        ('production', '0017_historicalworkcenter_workcenter_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status', 'created_at'], name='idx_serial_status_date'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['product', 'status'], name='idx_serial_product_status'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['status', 'created_at'], name='idx_sc_status_date'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['warehouse', 'count_date'], name='idx_sc_warehouse_date'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product', 'received_date'], name='idx_lot_product_date'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['warehouse', 'received_date'], name='idx_lot_warehouse_date'),
        ),
    ]
