# Generated by Django 5.2.12 on 2026-04-16 01:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_serialnumber_idx_serial_status_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBasisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stage', models.CharField(choices=[('QUOTATION', '견적'), ('ORDER', '주문'), ('PRODUCTION', '생산'), ('SETTLEMENT', '정산')], max_length=20, unique=True, verbose_name='적용단계')),
                ('primary_basis', models.CharField(choices=[('PRODUCT', '제품 현재원가'), ('BOM', 'BOM 자재원가'), ('STANDARD', '표준원가'), ('PRODUCTION', '최근 생산원가')], default='PRODUCT', max_length=20, verbose_name='1순위 원가기준')),
                ('fallback_basis', models.CharField(choices=[('PRODUCT', '제품 현재원가'), ('BOM', 'BOM 자재원가'), ('STANDARD', '표준원가'), ('PRODUCTION', '최근 생산원가')], default='BOM', help_text='1순위 원가가 없을 때 적용', max_length=20, verbose_name='2순위 원가기준')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '원가기준설정',
                'verbose_name_plural': '원가기준설정',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCostBasisConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('stage', models.CharField(choices=[('QUOTATION', '견적'), ('ORDER', '주문'), ('PRODUCTION', '생산'), ('SETTLEMENT', '정산')], db_index=True, max_length=20, verbose_name='적용단계')),
                ('primary_basis', models.CharField(choices=[('PRODUCT', '제품 현재원가'), ('BOM', 'BOM 자재원가'), ('STANDARD', '표준원가'), ('PRODUCTION', '최근 생산원가')], default='PRODUCT', max_length=20, verbose_name='1순위 원가기준')),
                ('fallback_basis', models.CharField(choices=[('PRODUCT', '제품 현재원가'), ('BOM', 'BOM 자재원가'), ('STANDARD', '표준원가'), ('PRODUCTION', '최근 생산원가')], default='BOM', help_text='1순위 원가가 없을 때 적용', max_length=20, verbose_name='2순위 원가기준')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 원가기준설정',
                'verbose_name_plural': 'historical 원가기준설정',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
