# Generated by Django 5.2.12 on 2026-04-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_cost_basis_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='auto_standard_cost',
            field=models.BooleanField(default=False, help_text='활성화 시 원가 변동 시 표준원가 자동 생성/갱신', verbose_name='표준원가 자동갱신'),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_standard_cost',
            field=models.BooleanField(default=False, help_text='활성화 시 원가 변동 시 표준원가 자동 생성/갱신', verbose_name='표준원가 자동갱신'),
        ),
    ]
