# Generated by Django 5.2.12 on 2026-04-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_product_auto_standard_cost'),
        ('production', '0019_historicalproductionbatch_productionbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserialnumber',
            name='production_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionbatch', verbose_name='생산배치'),
        ),
        migrations.AddField(
            model_name='historicalstocklot',
            name='production_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionbatch', verbose_name='생산배치'),
        ),
        migrations.AddField(
            model_name='historicalstockmovement',
            name='production_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionbatch', verbose_name='생산배치'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='production.productionbatch', verbose_name='생산배치'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='production.productionbatch', verbose_name='생산배치'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='production.productionbatch', verbose_name='생산배치'),
        ),
    ]
