# Generated by Django 5.2.12 on 2026-04-24 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_historicalserialnumber_production_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockmovement',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='출고 시 소진된 StockLot 기반 실제 원가 합계 (FIFO/LIFO)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='매출원가금액'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='출고 시 소진된 StockLot 기반 실제 원가 합계 (FIFO/LIFO)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='매출원가금액'),
        ),
    ]
