# Generated by Django 5.2.12 on 2026-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_historicalstockmovement_cogs_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='net_realizable_value',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='기말 재고평가 기준 — 예상 판매가 − 예상 판매비용. 공란 시 평가손실 계산 제외.', max_digits=12, null=True, verbose_name='순실현가능가액(NRV)'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_realizable_value',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='기말 재고평가 기준 — 예상 판매가 − 예상 판매비용. 공란 시 평가손실 계산 제외.', max_digits=12, null=True, verbose_name='순실현가능가액(NRV)'),
        ),
    ]
