# Generated by Django 5.2.12 on 2026-04-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportschedule',
            options={'ordering': ['-updated_at'], 'verbose_name': '리포트스케줄', 'verbose_name_plural': '리포트스케줄'},
        ),
    ]
