# Generated by Django 5.2.12 on 2026-04-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmilestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='document.contract', verbose_name='계약'),
        ),
        migrations.AlterField(
            model_name='documentapproval',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='document.document', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='document.document', verbose_name='문서'),
        ),
    ]
