# Generated by Django 5.2.12 on 2026-04-15 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_employeeprofile_idx_emp_dept_date_and_more'),
        ('project', '0002_alter_milestone_project_alter_projectmember_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager', 'status'], name='idx_project_mgr_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'due_date'], name='idx_project_status_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='idx_task_project_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'due_date'], name='idx_task_assignee_due'),
        ),
    ]
