# Generated by Django 5.2.12 on 2026-03-19 04:25

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="bank_account",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="계좌번호"
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="emergency_contact",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="비상연락처"
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployeeprofile",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="historicalemployeeprofile",
            name="bank_account",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="계좌번호"
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployeeprofile",
            name="emergency_contact",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="비상연락처"
            ),
        ),
    ]
