# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeeprofile_idx_employee_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='사번'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='사번'),
        ),
    ]
