# Generated by Django 5.2.12 on 2026-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_number_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='level',
            field=models.PositiveIntegerField(help_text='1=최상위, 숫자가 클수록 낮은 직급', verbose_name='레벨'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.PositiveIntegerField(help_text='1=최상위, 숫자가 클수록 낮은 직급', verbose_name='레벨'),
        ),
    ]
