# Generated by Django 5.2.12 on 2026-03-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonnelaction',
            name='action_type',
            field=models.CharField(choices=[('HIRE', '입사'), ('PROMOTION', '승진'), ('TRANSFER', '전보'), ('DEMOTION', '강등'), ('MANAGER_APPOINT', '부서장 임명'), ('RESIGNATION', '퇴사'), ('LEAVE', '휴직'), ('RETURN', '복직')], max_length=20, verbose_name='발령유형'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='action_type',
            field=models.CharField(choices=[('HIRE', '입사'), ('PROMOTION', '승진'), ('TRANSFER', '전보'), ('DEMOTION', '강등'), ('MANAGER_APPOINT', '부서장 임명'), ('RESIGNATION', '퇴사'), ('LEAVE', '휴직'), ('RETURN', '복직')], max_length=20, verbose_name='발령유형'),
        ),
    ]
