# Generated by Django 5.2.12 on 2026-03-28 10:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_historicalpersonnelaction_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='계약종료일'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='계약시작일'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.CharField(choices=[('INTERNAL', '정규직'), ('CONTRACT', '계약직'), ('EXTERNAL', '외부협력'), ('DISPATCH', '파견')], default='INTERNAL', max_length=20, verbose_name='고용유형'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='계약종료일'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='계약시작일'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='employee_type',
            field=models.CharField(choices=[('INTERNAL', '정규직'), ('CONTRACT', '계약직'), ('EXTERNAL', '외부협력'), ('DISPATCH', '파견')], default='INTERNAL', max_length=20, verbose_name='고용유형'),
        ),
        migrations.AlterField(
            model_name='historicalpersonnelaction',
            name='action_type',
            field=models.CharField(choices=[('HIRE', '입사'), ('PROMOTION', '승진'), ('TRANSFER', '전보'), ('DEMOTION', '강등'), ('MANAGER_APPOINT', '부서장 임명'), ('RESIGNATION', '퇴사'), ('LEAVE', '휴직'), ('RETURN', '복직'), ('DISPATCH_IN', '파견입사'), ('DISPATCH_EXTEND', '파견연장'), ('DISPATCH_END', '파견종료'), ('EXTERNAL_IN', '외부인력 투입'), ('EXTERNAL_OUT', '외부인력 철수')], max_length=20, verbose_name='발령유형'),
        ),
        migrations.AlterField(
            model_name='personnelaction',
            name='action_type',
            field=models.CharField(choices=[('HIRE', '입사'), ('PROMOTION', '승진'), ('TRANSFER', '전보'), ('DEMOTION', '강등'), ('MANAGER_APPOINT', '부서장 임명'), ('RESIGNATION', '퇴사'), ('LEAVE', '휴직'), ('RETURN', '복직'), ('DISPATCH_IN', '파견입사'), ('DISPATCH_EXTEND', '파견연장'), ('DISPATCH_END', '파견종료'), ('EXTERNAL_IN', '외부인력 투입'), ('EXTERNAL_OUT', '외부인력 철수')], max_length=20, verbose_name='발령유형'),
        ),
        migrations.CreateModel(
            name='ExternalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('business_number', models.CharField(max_length=20, unique=True, verbose_name='사업자번호')),
                ('representative', models.CharField(max_length=50, verbose_name='대표자')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='계약시작일')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='계약종료일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '외부 협력업체',
                'verbose_name_plural': '외부 협력업체',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='external_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.externalcompany', verbose_name='소속 외부업체'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='external_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.externalcompany', verbose_name='소속 외부업체'),
        ),
        migrations.CreateModel(
            name='HistoricalExternalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('business_number', models.CharField(db_index=True, max_length=20, verbose_name='사업자번호')),
                ('representative', models.CharField(max_length=50, verbose_name='대표자')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='계약시작일')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='계약종료일')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 외부 협력업체',
                'verbose_name_plural': 'historical 외부 협력업체',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
