# Generated by Django 5.2.12 on 2026-04-15 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_historicallaborconfig_historicalseverancepay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['department', 'created_at'], name='idx_emp_dept_date'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['status', 'created_at'], name='idx_emp_status_date'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'year'], name='idx_payroll_emp_year'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status', 'year'], name='idx_payroll_status_year'),
        ),
        migrations.AddIndex(
            model_name='personnelaction',
            index=models.Index(fields=['employee', 'effective_date'], name='idx_action_emp_date'),
        ),
        migrations.AddIndex(
            model_name='personnelaction',
            index=models.Index(fields=['action_type', 'effective_date'], name='idx_action_type_date'),
        ),
    ]
