# Generated by Django 5.2.12 on 2026-03-17 06:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=200, verbose_name="캠페인명")),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("BRAND", "브랜드"),
                            ("PRODUCT", "제품"),
                            ("RETARGETING", "리타겟팅"),
                            ("SEASONAL", "시즌"),
                            ("PROMOTION", "프로모션"),
                        ],
                        default="PRODUCT",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "진행중"),
                            ("PAUSED", "일시정지"),
                            ("COMPLETED", "완료"),
                            ("ARCHIVED", "보관"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="예산"
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="집행액",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "target_audience",
                    models.TextField(blank=True, verbose_name="타겟 오디언스"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 캠페인",
                "verbose_name_plural": "광고 캠페인",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AdCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=200, verbose_name="소재명")),
                (
                    "creative_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "이미지"),
                            ("VIDEO", "동영상"),
                            ("TEXT", "텍스트"),
                            ("CAROUSEL", "캐러셀"),
                            ("RESPONSIVE", "반응형"),
                        ],
                        default="IMAGE",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("headline", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("landing_url", models.URLField(blank=True, verbose_name="랜딩 URL")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="advertising/creatives/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "활성"),
                            ("PAUSED", "일시정지"),
                            ("REJECTED", "반려"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="advertising.adcampaign",
                        verbose_name="캠페인",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 소재",
                "verbose_name_plural": "광고 소재",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="플랫폼명")),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("SEARCH", "검색광고"),
                            ("DISPLAY", "디스플레이"),
                            ("SOCIAL", "소셜미디어"),
                            ("VIDEO", "동영상"),
                            ("OTHER", "기타"),
                        ],
                        default="SEARCH",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=255, verbose_name="API 키"),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API 시크릿"
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="계정 ID"
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(default=False, verbose_name="연동 상태"),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="플랫폼 URL")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 플랫폼",
                "verbose_name_plural": "광고 플랫폼",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="advertising.adplatform",
                verbose_name="플랫폼",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAdBudget",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "planned_budget",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="계획 예산",
                    ),
                ),
                (
                    "actual_spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="실제 집행",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="advertising.adplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 광고 예산",
                "verbose_name_plural": "historical 광고 예산",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAdCampaign",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=200, verbose_name="캠페인명")),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("BRAND", "브랜드"),
                            ("PRODUCT", "제품"),
                            ("RETARGETING", "리타겟팅"),
                            ("SEASONAL", "시즌"),
                            ("PROMOTION", "프로모션"),
                        ],
                        default="PRODUCT",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "진행중"),
                            ("PAUSED", "일시정지"),
                            ("COMPLETED", "완료"),
                            ("ARCHIVED", "보관"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="예산"
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="집행액",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "target_audience",
                    models.TextField(blank=True, verbose_name="타겟 오디언스"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="advertising.adplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 광고 캠페인",
                "verbose_name_plural": "historical 광고 캠페인",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAdCreative",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=200, verbose_name="소재명")),
                (
                    "creative_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "이미지"),
                            ("VIDEO", "동영상"),
                            ("TEXT", "텍스트"),
                            ("CAROUSEL", "캐러셀"),
                            ("RESPONSIVE", "반응형"),
                        ],
                        default="IMAGE",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                ("headline", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("landing_url", models.URLField(blank=True, verbose_name="랜딩 URL")),
                (
                    "image",
                    models.TextField(blank=True, max_length=100, verbose_name="이미지"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("ACTIVE", "활성"),
                            ("PAUSED", "일시정지"),
                            ("REJECTED", "반려"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="advertising.adcampaign",
                        verbose_name="캠페인",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 광고 소재",
                "verbose_name_plural": "historical 광고 소재",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAdPerformance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("date", models.DateField(verbose_name="날짜")),
                ("impressions", models.IntegerField(default=0, verbose_name="노출수")),
                ("clicks", models.IntegerField(default=0, verbose_name="클릭수")),
                ("conversions", models.IntegerField(default=0, verbose_name="전환수")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="비용"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="매출"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="advertising.adcampaign",
                        verbose_name="캠페인",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="advertising.adcreative",
                        verbose_name="소재",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 광고 성과",
                "verbose_name_plural": "historical 광고 성과",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAdPlatform",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="수정일"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("name", models.CharField(max_length=100, verbose_name="플랫폼명")),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("SEARCH", "검색광고"),
                            ("DISPLAY", "디스플레이"),
                            ("SOCIAL", "소셜미디어"),
                            ("VIDEO", "동영상"),
                            ("OTHER", "기타"),
                        ],
                        default="SEARCH",
                        max_length=20,
                        verbose_name="유형",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=255, verbose_name="API 키"),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API 시크릿"
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="계정 ID"
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(default=False, verbose_name="연동 상태"),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="플랫폼 URL")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 광고 플랫폼",
                "verbose_name_plural": "historical 광고 플랫폼",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AdPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("date", models.DateField(verbose_name="날짜")),
                ("impressions", models.IntegerField(default=0, verbose_name="노출수")),
                ("clicks", models.IntegerField(default=0, verbose_name="클릭수")),
                ("conversions", models.IntegerField(default=0, verbose_name="전환수")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="비용"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="매출"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="advertising.adcampaign",
                        verbose_name="캠페인",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performances",
                        to="advertising.adcreative",
                        verbose_name="소재",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 성과",
                "verbose_name_plural": "광고 성과",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "date"], name="idx_adperf_campaign_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                ("year", models.IntegerField(verbose_name="연도")),
                ("month", models.IntegerField(verbose_name="월")),
                (
                    "planned_budget",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="계획 예산",
                    ),
                ),
                (
                    "actual_spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="실제 집행",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="advertising.adplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "광고 예산",
                "verbose_name_plural": "광고 예산",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month", "platform")},
            },
        ),
    ]
