# Generated by Django 5.2.12 on 2026-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbudget',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='historicaladbudget',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], verbose_name='월'),
        ),
    ]
