# Generated by Django 5.2.12 on 2026-03-19 04:14

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0002_alter_adbudget_month_alter_historicaladbudget_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adplatform",
            name="api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API 키"
            ),
        ),
        migrations.AlterField(
            model_name="adplatform",
            name="api_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API 시크릿"
            ),
        ),
        migrations.AlterField(
            model_name="historicaladplatform",
            name="api_key",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API 키"
            ),
        ),
        migrations.AlterField(
            model_name="historicaladplatform",
            name="api_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True, max_length=500, verbose_name="API 시크릿"
            ),
        ),
    ]
