# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_alter_adplatform_api_key_alter_adplatform_api_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreative',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.core.storage.hashed_upload_path('advertising/creatives'), verbose_name='이미지'),
        ),
    ]
