# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalation_rules', to='helpdesk.ticketcategory', verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='helpdesk.ticket', verbose_name='티켓'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='helpdesk.ticket', verbose_name='티켓'),
        ),
    ]
