# Generated by Django 5.2.12 on 2026-04-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_escalationrule_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escalationrule',
            unique_together={('category', 'condition_type')},
        ),
    ]
