# Generated by Django 5.2.12 on 2026-04-14 01:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_escalationrule_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSLABreach',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('breach_type', models.CharField(choices=[('RESPONSE', '응답시간 초과'), ('RESOLUTION', '해결시간 초과')], max_length=10, verbose_name='위반 유형')),
                ('breached_at', models.DateTimeField(blank=True, editable=False, verbose_name='위반 시각')),
                ('notified', models.BooleanField(default=False, verbose_name='알림 발송')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sla', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.sla', verbose_name='SLA')),
                ('ticket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.ticket', verbose_name='티켓')),
            ],
            options={
                'verbose_name': 'historical SLA 위반',
                'verbose_name_plural': 'historical SLA 위반',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('breach_type', models.CharField(choices=[('RESPONSE', '응답시간 초과'), ('RESOLUTION', '해결시간 초과')], max_length=10, verbose_name='위반 유형')),
                ('breached_at', models.DateTimeField(auto_now_add=True, verbose_name='위반 시각')),
                ('notified', models.BooleanField(default=False, verbose_name='알림 발송')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaches', to='helpdesk.sla', verbose_name='SLA')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_breaches', to='helpdesk.ticket', verbose_name='티켓')),
            ],
            options={
                'verbose_name': 'SLA 위반',
                'verbose_name_plural': 'SLA 위반',
                'ordering': ['-breached_at'],
                'unique_together': {('ticket', 'breach_type')},
            },
        ),
    ]
