# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edimapping',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='edi.edidocumenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='edischedule',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='edi.edidocumenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='edischedule',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='edi.edipartner', verbose_name='EDI 거래처'),
        ),
    ]
