# Generated by Django 5.2.12 on 2026-04-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0002_alter_edimapping_document_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edischedule',
            unique_together={('partner', 'document_type')},
        ),
    ]
