# Generated by Django 5.2.13 on 2026-05-05 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0003_alter_edischedule_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edimapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type', 'source_field', 'target_model', 'target_field'), name='uq_edi_mapping_doc_src_tgt'),
        ),
    ]
