# Generated by Django 5.2.12 on 2026-03-16 12:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_datetime', models.DateTimeField(verbose_name='시작일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료일시')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일')),
                ('event_type', models.CharField(choices=[('personal', '개인'), ('team', '팀'), ('company', '회사'), ('meeting', '회의')], default='personal', max_length=20, verbose_name='일정 유형')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='색상')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='반복 일정')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_datetime', models.DateTimeField(verbose_name='시작일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료일시')),
                ('all_day', models.BooleanField(default=False, verbose_name='종일')),
                ('event_type', models.CharField(choices=[('personal', '개인'), ('team', '팀'), ('company', '회사'), ('meeting', '회의')], default='personal', max_length=20, verbose_name='일정 유형')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='색상')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='반복 일정')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 일정',
                'verbose_name_plural': 'historical 일정',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
