# Generated by Django 5.2.12 on 2026-03-19 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='idx_attendance_status'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='idx_leave_status'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['user', 'start_date'], name='idx_leave_user_date'),
        ),
    ]
