# Generated by Django 5.2.12 on 2026-03-23 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_idx_attendance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualleavebalance',
            options={'ordering': ['-year'], 'verbose_name': '연차 잔여', 'verbose_name_plural': '연차 잔여'},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uq_attendance_user_date'),
        ),
    ]
