# Generated by Django 5.2.12 on 2026-04-15 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_annualleavebalance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annualleavebalance',
            index=models.Index(fields=['user', 'year'], name='idx_leave_bal_user_year'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'date'], name='idx_attend_user_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', 'date'], name='idx_attend_status_date'),
        ),
    ]
