# Generated by Django 5.2.12 on 2026-04-28 06:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(help_text='2자리 알파벳 (KR, US, JP, ...)', max_length=2, unique=True, verbose_name='국가코드 (ISO-3166)')),
                ('name', models.CharField(max_length=100, verbose_name='국가명')),
                ('currency_code', models.CharField(help_text='KRW, USD, JPY, ...', max_length=3, verbose_name='기본통화 (ISO-4217)')),
                ('locale', models.CharField(help_text='ko_KR, en_US, ja_JP, ...', max_length=10, verbose_name='로케일')),
                ('is_default', models.BooleanField(default=False, help_text='시스템 default 국가 (단일 행만 True)', verbose_name='기본 국가')),
                ('is_supported', models.BooleanField(default=False, help_text='LocalizationAdapter 구현 여부 (False면 기능 제한)', verbose_name='어댑터 구현됨')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('code', models.CharField(db_index=True, help_text='2자리 알파벳 (KR, US, JP, ...)', max_length=2, verbose_name='국가코드 (ISO-3166)')),
                ('name', models.CharField(max_length=100, verbose_name='국가명')),
                ('currency_code', models.CharField(help_text='KRW, USD, JPY, ...', max_length=3, verbose_name='기본통화 (ISO-4217)')),
                ('locale', models.CharField(help_text='ko_KR, en_US, ja_JP, ...', max_length=10, verbose_name='로케일')),
                ('is_default', models.BooleanField(default=False, help_text='시스템 default 국가 (단일 행만 True)', verbose_name='기본 국가')),
                ('is_supported', models.BooleanField(default=False, help_text='LocalizationAdapter 구현 여부 (False면 기능 제한)', verbose_name='어댑터 구현됨')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 국가',
                'verbose_name_plural': 'historical 국가',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
