# Generated by Django 5.2.12 on 2026-03-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptitem',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.goodsreceipt', verbose_name='입고확인'),
        ),
        migrations.AlterField(
            model_name='historicalgoodsreceiptitem',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.goodsreceipt', verbose_name='입고확인'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorder', verbose_name='발주서'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder', verbose_name='발주서'),
        ),
    ]
