# Generated by Django 5.2.12 on 2026-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_historicalpurchaseorderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='입고번호'),
        ),
        migrations.AlterField(
            model_name='historicalgoodsreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='입고번호'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='발주번호'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='발주번호'),
        ),
    ]
