# Generated by Django 5.2.12 on 2026-03-22 01:54

from django.db import migrations
from django.utils import timezone


# (모델명, 번호필드명, 접두사) 매핑
MODELS_TO_CONVERT = [
    ('PurchaseOrder', 'po_number', 'PO'),
    ('GoodsReceipt', 'receipt_number', 'GR'),
]


def convert_numbers(apps, schema_editor):
    """기존 문서번호를 새 형식(PREFIX-YYYYMMDD-NNN)으로 변환"""
    today = timezone.localdate().strftime('%Y%m%d')

    for model_name, field_name, prefix in MODELS_TO_CONVERT:
        Model = apps.get_model('purchase', model_name)
        pattern = f'{prefix}-'

        # 이미 새 형식인 레코드는 건너뛰기
        objects = Model.objects.exclude(
            **{f'{field_name}__startswith': pattern}
        ).order_by('pk')

        for seq, obj in enumerate(objects, start=1):
            new_number = f'{prefix}-{today}-{seq:03d}'
            setattr(obj, field_name, new_number)
            obj.save(update_fields=[field_name])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_goodsreceipt_receipt_number_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_numbers, noop),
    ]
