# Generated by Django 5.2.12 on 2026-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_number_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorderitem',
            name='receipt_file',
            field=models.TextField(blank=True, max_length=100, verbose_name='영수증'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to='receipts/purchase/', verbose_name='영수증'),
        ),
    ]
