# Generated by Django 5.2.12 on 2026-03-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_add_receipt_file_and_status_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주하여 역산합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주하여 역산합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
    ]
