# Generated by Django 5.2.12 on 2026-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_add_vat_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, verbose_name='품의서/첨부파일'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to='purchase/attachments/', verbose_name='품의서/첨부파일'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vat_included',
            field=models.BooleanField(default=False, help_text='체크 시 입력 금액을 VAT 포함 금액으로 간주합니다.', verbose_name='VAT 포함 금액 입력'),
        ),
    ]
