# Generated by Django 5.2.12 on 2026-03-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_number_convert'),
        ('purchase', '0008_add_po_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='approval_request',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'PURCHASE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='approval.approvalrequest', verbose_name='품의서'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_request',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PURCHASE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='approval.approvalrequest', verbose_name='품의서'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to='purchase/attachments/', verbose_name='첨부파일'),
        ),
    ]
