# Generated by Django 5.2.12 on 2026-03-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_historicalproduct_current_stock_and_more'),
        ('purchase', '0009_add_approval_request_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'ordering': ['-receipt_number'], 'verbose_name': '입고확인', 'verbose_name_plural': '입고확인'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-po_number'], 'verbose_name': '발주서', 'verbose_name_plural': '발주서'},
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='입고 대상 창고', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='입고창고'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='입고 대상 창고', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='입고창고'),
        ),
    ]
