# Generated by Django 5.2.12 on 2026-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_goodsreceipt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceiptitem',
            options={'ordering': ['pk'], 'verbose_name': '입고항목', 'verbose_name_plural': '입고항목'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['pk'], 'verbose_name': '발주항목', 'verbose_name_plural': '발주항목'},
        ),
    ]
