# Generated by Django 5.2.12 on 2026-03-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_currency_historicalcurrency_historicalexchangerate_and_more'),
        ('purchase', '0011_alter_goodsreceiptitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency', verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='적용환율'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency', verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='적용환율'),
        ),
    ]
