# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_historicalpurchaseorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='첨부파일 원본명'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='첨부파일 원본명'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.core.storage.hashed_upload_path('purchase/attachments'), verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to=apps.core.storage.hashed_upload_path('receipts/purchase'), verbose_name='영수증'),
        ),
    ]
