# Generated by Django 5.2.12 on 2026-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_historicalpurchaseorder_attachment_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='면세(중고거래, 개인 간 현금거래 등)인 경우 해제', verbose_name='과세 거래'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='면세(중고거래, 개인 간 현금거래 등)인 경우 해제', verbose_name='과세 거래'),
        ),
    ]
