# Generated by Django 5.2.12 on 2026-04-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_fixedasset_condition_assessment_and_more'),
        ('purchase', '0014_add_is_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.assetcategory', verbose_name='자산분류'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='is_fixed_asset',
            field=models.BooleanField(default=False, verbose_name='자산등록'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptitem',
            name='asset_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetcategory', verbose_name='자산분류'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptitem',
            name='is_fixed_asset',
            field=models.BooleanField(default=False, verbose_name='자산등록'),
        ),
    ]
