# Generated by Django 5.2.12 on 2026-04-15 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_serialnumber_idx_serial_status_date_and_more'),
        ('purchase', '0016_historicalrfq_historicalvendorscore_rfq_and_more'),
        ('sales', '0046_historicalpartner_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['receipt_date'], name='idx_gr_receipt_date'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order', 'receipt_date'], name='idx_gr_po_date'),
        ),
        migrations.AddIndex(
            model_name='rfqresponse',
            index=models.Index(fields=['rfq', 'is_selected'], name='idx_rfqresp_rfq_selected'),
        ),
    ]
