# Generated by Django 5.2.12 on 2026-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_goodsreceipt_idx_gr_receipt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='vat_deduction_type',
            field=models.CharField(choices=[('DEDUCTIBLE', '일반매입(공제)'), ('DEEMED', '의제매입세액(면세 농축수산물)'), ('NON_DEDUCTIBLE', '공제받지못할매입(접대비·사업무관)')], default='DEDUCTIBLE', help_text='부가세 신고 시 매입세액 구분 — 의제/불공제는 별도 집계', max_length=20, verbose_name='매입세액 구분'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_deduction_type',
            field=models.CharField(choices=[('DEDUCTIBLE', '일반매입(공제)'), ('DEEMED', '의제매입세액(면세 농축수산물)'), ('NON_DEDUCTIBLE', '공제받지못할매입(접대비·사업무관)')], default='DEDUCTIBLE', help_text='부가세 신고 시 매입세액 구분 — 의제/불공제는 별도 집계', max_length=20, verbose_name='매입세액 구분'),
        ),
    ]
