# Generated by Django 5.2.12 on 2026-03-22 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_number_convert'),
        ('hr', '0005_auto_number_convert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-request_number'], 'verbose_name': '결재/품의', 'verbose_name_plural': '결재/품의'},
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='cooperator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_cooperated', to=settings.AUTH_USER_MODEL, verbose_name='협조자'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='기안부서'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='expected_date',
            field=models.DateField(blank=True, help_text='집행/납품 희망일', null=True, verbose_name='희망일자'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='purpose',
            field=models.TextField(blank=True, help_text='품의를 올리는 목적 또는 사유', verbose_name='품의목적/사유'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='urgency',
            field=models.CharField(choices=[('NORMAL', '일반'), ('URGENT', '긴급'), ('CRITICAL', '특급')], default='NORMAL', max_length=10, verbose_name='긴급도'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='cooperator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='협조자'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.department', verbose_name='기안부서'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='expected_date',
            field=models.DateField(blank=True, help_text='집행/납품 희망일', null=True, verbose_name='희망일자'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='purpose',
            field=models.TextField(blank=True, help_text='품의를 올리는 목적 또는 사유', verbose_name='품의목적/사유'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='urgency',
            field=models.CharField(choices=[('NORMAL', '일반'), ('URGENT', '긴급'), ('CRITICAL', '특급')], default='NORMAL', max_length=10, verbose_name='긴급도'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='content',
            field=models.TextField(verbose_name='세부내용'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='기안자'),
        ),
        migrations.AlterField(
            model_name='historicalapprovalrequest',
            name='content',
            field=models.TextField(verbose_name='세부내용'),
        ),
        migrations.AlterField(
            model_name='historicalapprovalrequest',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='기안자'),
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('file', models.FileField(upload_to='approval/attachments/%Y/%m/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본파일명')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approval.approvalrequest', verbose_name='결재요청')),
            ],
            options={
                'verbose_name': '결재 첨부파일',
                'verbose_name_plural': '결재 첨부파일',
                'ordering': ['pk'],
            },
        ),
    ]
