# Generated by Django 5.2.12 on 2026-03-29 01:57

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_enhance_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.storage.hashed_upload_path('approval/attachments'), verbose_name='파일'),
        ),
    ]
