# Generated by Django 5.2.12 on 2026-04-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_approvalattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='category',
            field=models.CharField(choices=[('PURCHASE', '구매품의'), ('EXPENSE', '지출품의'), ('BUDGET', '예산신청'), ('CONTRACT', '계약체결'), ('GENERAL', '일반결재'), ('LEAVE', '휴가신청'), ('OVERTIME', '초과근무'), ('TRAVEL', '출장신청'), ('IT_REQUEST', 'IT요청'), ('ASSET_DISPOSAL', '자산처분')], max_length=20, verbose_name='문서종류'),
        ),
        migrations.AlterField(
            model_name='historicalapprovalrequest',
            name='category',
            field=models.CharField(choices=[('PURCHASE', '구매품의'), ('EXPENSE', '지출품의'), ('BUDGET', '예산신청'), ('CONTRACT', '계약체결'), ('GENERAL', '일반결재'), ('LEAVE', '휴가신청'), ('OVERTIME', '초과근무'), ('TRAVEL', '출장신청'), ('IT_REQUEST', 'IT요청'), ('ASSET_DISPOSAL', '자산처분')], max_length=20, verbose_name='문서종류'),
        ),
    ]
