# Generated by Django 5.2.12 on 2026-04-20 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_approvaldelegation_approvallinetemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallinetemplate',
            options={'ordering': ['-priority', '-is_default', 'name'], 'verbose_name': '결재선 템플릿', 'verbose_name_plural': '결재선 템플릿'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['step_order', 'pk'], 'verbose_name': '결재단계', 'verbose_name_plural': '결재단계'},
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvallinetemplate',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='기안 생성 시 condition 매칭 템플릿을 자동 적용', verbose_name='자동적용'),
        ),
        migrations.AddField(
            model_name='approvallinetemplate',
            name='condition',
            field=models.JSONField(blank=True, default=dict, verbose_name='자동적용 조건'),
        ),
        migrations.AddField(
            model_name='approvallinetemplate',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='높을수록 우선. 여러 템플릿이 매칭되면 우선순위 높은 것부터 1건 사용', verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('SEQUENTIAL', '직렬'), ('PARALLEL_ALL', '병렬(전원합의)'), ('PARALLEL_ANY', '병렬(1인결재)')], default='SEQUENTIAL', help_text='직렬 / 병렬(전원합의) / 병렬(1인결재)', max_length=20, verbose_name='결재방식'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='delegated_from',
            field=models.ForeignKey(blank=True, help_text='위임으로 치환된 경우 원래 결재자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_delegated_to_me', to=settings.AUTH_USER_MODEL, verbose_name='원결재자'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_created', to='approval.approvaldelegation', verbose_name='위임정보'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='parallel_mode',
            field=models.CharField(choices=[('SEQUENTIAL', '직렬'), ('ALL', '전원합의'), ('ANY', '1인결재')], default='SEQUENTIAL', help_text='같은 단계에 다중 결재자일 때의 합의 방식', max_length=20, verbose_name='병렬모드'),
        ),
        migrations.AddField(
            model_name='historicalapprovallinetemplate',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='기안 생성 시 condition 매칭 템플릿을 자동 적용', verbose_name='자동적용'),
        ),
        migrations.AddField(
            model_name='historicalapprovallinetemplate',
            name='condition',
            field=models.JSONField(blank=True, default=dict, verbose_name='자동적용 조건'),
        ),
        migrations.AddField(
            model_name='historicalapprovallinetemplate',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='높을수록 우선. 여러 템플릿이 매칭되면 우선순위 높은 것부터 1건 사용', verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='historicalapprovalrequest',
            name='approval_type',
            field=models.CharField(choices=[('SEQUENTIAL', '직렬'), ('PARALLEL_ALL', '병렬(전원합의)'), ('PARALLEL_ANY', '병렬(1인결재)')], default='SEQUENTIAL', help_text='직렬 / 병렬(전원합의) / 병렬(1인결재)', max_length=20, verbose_name='결재방식'),
        ),
        migrations.AddField(
            model_name='historicalapprovalstep',
            name='delegated_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='위임으로 치환된 경우 원래 결재자', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='원결재자'),
        ),
        migrations.AddField(
            model_name='historicalapprovalstep',
            name='delegation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='approval.approvaldelegation', verbose_name='위임정보'),
        ),
        migrations.AddField(
            model_name='historicalapprovalstep',
            name='parallel_mode',
            field=models.CharField(choices=[('SEQUENTIAL', '직렬'), ('ALL', '전원합의'), ('ANY', '1인결재')], default='SEQUENTIAL', help_text='같은 단계에 다중 결재자일 때의 합의 방식', max_length=20, verbose_name='병렬모드'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('SKIPPED', '건너뜀')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='historicalapprovalstep',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('SKIPPED', '건너뜀')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
    ]
