# Generated by Django 5.2.12 on 2026-04-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='subscription.subscription', verbose_name='구독'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='subscription.subscription', verbose_name='구독'),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='subscription.subscription', verbose_name='구독'),
        ),
    ]
