# Generated by Django 5.2.12 on 2026-04-29 07:05

import apps.localizations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_billingrecord_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='currency',
            field=models.CharField(default=apps.localizations.get_default_currency_code, max_length=3, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default=apps.localizations.get_default_currency_code, max_length=3, verbose_name='통화'),
        ),
    ]
